In [ ]:
import pandas as pd

In [ ]:
student_df = pd.read_excel("student_records_20.xlsx")
student_df

,student_id,name,branch,course,fees,paid_fees
0,1001,Aarav Sharma,Karve Nagar,NaN,40000.0,30000
1,1002,Priya Patil,Hadapsar,Data Science,50000.0,45000
2,1003,Rohan Joshi,Chinchwad,Python Full Stack,30000.0,25000
3,1004,Sneha Kulkarni,NaN,Java Full Stack,NaN,20000
4,1005,Aditya More,Karve Nagar,Testing,25000.0,25000
5,1005,Aditya More,Karve Nagar,Testing,25000.0,25000
6,1006,Neha Deshmukh,Hadapsar,Data Analytics,40000.0,35000
7,1007,Vikram Jadhav,Chinchwad,Data Science,50000.0,40000
8,1008,NaN,Nagpur,NaN,30000.0,28000
9,1008,Pooja Pawar,Nagpur,Python Full Stack,30000.0,28000
10,1009,Rahul Shinde,Karve Nagar,Java Full Stack,30000.0,22000
11,1010,Kavya Wagh,Hadapsar,Testing,25000.0,15000
12,1011,Siddhant Kale,Chinchwad,Data Analytics,40000.0,30000
13,1012,Anjali Bhosale,NaN,Data Science,50000.0,50000
14,1013,Omkar Pawar,Karve Nagar,Python Full Stack,NaN,20000
15,1014,Isha Suryawanshi,Hadapsar,Java Full Stack,30000.0,27000
16,1015,Kunal Patil,Chinchwad,NaN,25000.0,20000
17,1016,Riya Chavan,Nagpur,Data Analytics,40000.0,32000
18,1016,Riya Chavan,Nagpur,Data Analytics,40000.0,32000
19,1017,Akash Thakur,Karve Nagar,Data Science,50000.0,35000
20,1018,Mitali Gaikwad,Hadapsar,Python Full Stack,30000.0,30000
21,1019,Nikhil Salunkhe,Chinchwad,Java Full Stack,30000.0,18000
22,1020,Tanvi Nikam,Nagpur,Testing,NaN,22000
23,1021,Yashasvi Dalvi,Karve Nagar,Data Analytics,40000.0,22000

In [ ]:
#null values are check
student_df.isnull().sum()

student_id    0
name          1
branch        2
course        3
fees          3
paid_fees     0
dtype: int64

In [ ]:
#dropna()
df = student_df["name"].dropna()
# df.isnull().sum()
df

0         Aarav Sharma
1          Priya Patil
2          Rohan Joshi
3       Sneha Kulkarni
4          Aditya More
5          Aditya More
6        Neha Deshmukh
7        Vikram Jadhav
9          Pooja Pawar
10        Rahul Shinde
11          Kavya Wagh
12       Siddhant Kale
13      Anjali Bhosale
14         Omkar Pawar
15    Isha Suryawanshi
16         Kunal Patil
17         Riya Chavan
18         Riya Chavan
19        Akash Thakur
20      Mitali Gaikwad
21     Nikhil Salunkhe
22         Tanvi Nikam
23      Yashasvi Dalvi
Name: name, dtype: str

In [ ]:
student_df["name"].fillna("Unknown")

0         Aarav Sharma
1          Priya Patil
2          Rohan Joshi
3       Sneha Kulkarni
4          Aditya More
5          Aditya More
6        Neha Deshmukh
7        Vikram Jadhav
8              Unknown
9          Pooja Pawar
10        Rahul Shinde
11          Kavya Wagh
12       Siddhant Kale
13      Anjali Bhosale
14         Omkar Pawar
15    Isha Suryawanshi
16         Kunal Patil
17         Riya Chavan
18         Riya Chavan
19        Akash Thakur
20      Mitali Gaikwad
21     Nikhil Salunkhe
22         Tanvi Nikam
23      Yashasvi Dalvi
Name: name, dtype: str

In [ ]:
course = student_df["course"].mode()
student_df["course"].fillna(course)
student_df

,student_id,name,branch,course,fees,paid_fees
0,1001,Aarav Sharma,Karve Nagar,NaN,40000.0,30000
1,1002,Priya Patil,Hadapsar,Data Science,50000.0,45000
2,1003,Rohan Joshi,Chinchwad,Python Full Stack,30000.0,25000
3,1004,Sneha Kulkarni,NaN,Java Full Stack,NaN,20000
4,1005,Aditya More,Karve Nagar,Testing,25000.0,25000
5,1005,Aditya More,Karve Nagar,Testing,25000.0,25000
6,1006,Neha Deshmukh,Hadapsar,Data Analytics,40000.0,35000
7,1007,Vikram Jadhav,Chinchwad,Data Science,50000.0,40000
8,1008,NaN,Nagpur,NaN,30000.0,28000
9,1008,Pooja Pawar,Nagpur,Python Full Stack,30000.0,28000
10,1009,Rahul Shinde,Karve Nagar,Java Full Stack,30000.0,22000
11,1010,Kavya Wagh,Hadapsar,Testing,25000.0,15000
12,1011,Siddhant Kale,Chinchwad,Data Analytics,40000.0,30000
13,1012,Anjali Bhosale,NaN,Data Science,50000.0,50000
14,1013,Omkar Pawar,Karve Nagar,Python Full Stack,NaN,20000
15,1014,Isha Suryawanshi,Hadapsar,Java Full Stack,30000.0,27000
16,1015,Kunal Patil,Chinchwad,NaN,25000.0,20000
17,1016,Riya Chavan,Nagpur,Data Analytics,40000.0,32000
18,1016,Riya Chavan,Nagpur,Data Analytics,40000.0,32000
19,1017,Akash Thakur,Karve Nagar,Data Science,50000.0,35000
20,1018,Mitali Gaikwad,Hadapsar,Python Full Stack,30000.0,30000
21,1019,Nikhil Salunkhe,Chinchwad,Java Full Stack,30000.0,18000
22,1020,Tanvi Nikam,Nagpur,Testing,NaN,22000
23,1021,Yashasvi Dalvi,Karve Nagar,Data Analytics,40000.0,22000

In [ ]:
branch = student_df["branch"].mode()
student_df["branch"].fillna(branch)

0     Karve Nagar
1        Hadapsar
2       Chinchwad
3             NaN
4     Karve Nagar
5     Karve Nagar
6        Hadapsar
7       Chinchwad
8          Nagpur
9          Nagpur
10    Karve Nagar
11       Hadapsar
12      Chinchwad
13            NaN
14    Karve Nagar
15       Hadapsar
16      Chinchwad
17         Nagpur
18         Nagpur
19    Karve Nagar
20       Hadapsar
21      Chinchwad
22         Nagpur
23    Karve Nagar
Name: branch, dtype: str

In [ ]:
student_df['course'].fillna(method = 'ffill')

TypeError: NDFrame.fillna() got an unexpected keyword argument 'method'

In [ ]:
avg = student_df['fees'].mean()
student_df['fees'].fillna(avg,inplace=True)

C:\Users\admin\AppData\Local\Temp\ipykernel_17860\1366865386.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  student_df['fees'].fillna(avg,inplace=True)

0     40000.000000
1     50000.000000
2     30000.000000
3     35714.285714
4     25000.000000
5     25000.000000
6     40000.000000
7     50000.000000
8     30000.000000
9     30000.000000
10    30000.000000
11    25000.000000
12    40000.000000
13    50000.000000
14    35714.285714
15    30000.000000
16    25000.000000
17    40000.000000
18    40000.000000
19    50000.000000
20    30000.000000
21    30000.000000
22    35714.285714
23    40000.000000
Name: fees, dtype: float64

In [ ]:
student_df

,student_id,name,branch,course,fees,paid_fees
0,1001,Aarav Sharma,Karve Nagar,NaN,40000.0,30000
1,1002,Priya Patil,Hadapsar,Data Science,50000.0,45000
2,1003,Rohan Joshi,Chinchwad,Python Full Stack,30000.0,25000
3,1004,Sneha Kulkarni,NaN,Java Full Stack,NaN,20000
4,1005,Aditya More,Karve Nagar,Testing,25000.0,25000
5,1005,Aditya More,Karve Nagar,Testing,25000.0,25000
6,1006,Neha Deshmukh,Hadapsar,Data Analytics,40000.0,35000
7,1007,Vikram Jadhav,Chinchwad,Data Science,50000.0,40000
8,1008,NaN,Nagpur,NaN,30000.0,28000
9,1008,Pooja Pawar,Nagpur,Python Full Stack,30000.0,28000
10,1009,Rahul Shinde,Karve Nagar,Java Full Stack,30000.0,22000
11,1010,Kavya Wagh,Hadapsar,Testing,25000.0,15000
12,1011,Siddhant Kale,Chinchwad,Data Analytics,40000.0,30000
13,1012,Anjali Bhosale,NaN,Data Science,50000.0,50000
14,1013,Omkar Pawar,Karve Nagar,Python Full Stack,NaN,20000
15,1014,Isha Suryawanshi,Hadapsar,Java Full Stack,30000.0,27000
16,1015,Kunal Patil,Chinchwad,NaN,25000.0,20000
17,1016,Riya Chavan,Nagpur,Data Analytics,40000.0,32000
18,1016,Riya Chavan,Nagpur,Data Analytics,40000.0,32000
19,1017,Akash Thakur,Karve Nagar,Data Science,50000.0,35000
20,1018,Mitali Gaikwad,Hadapsar,Python Full Stack,30000.0,30000
21,1019,Nikhil Salunkhe,Chinchwad,Java Full Stack,30000.0,18000
22,1020,Tanvi Nikam,Nagpur,Testing,NaN,22000
23,1021,Yashasvi Dalvi,Karve Nagar,Data Analytics,40000.0,22000

In [ ]:
student_df.duplicated().sum()

np.int64(2)

In [ ]:
student_df.drop_duplicates(inplace=True)

In [ ]:
student_df.duplicated().sum()

np.int64(0)

In [ ]:
student_df

,student_id,name,branch,course,fees,paid_fees
0,1001,Aarav Sharma,Karve Nagar,NaN,40000.0,30000
1,1002,Priya Patil,Hadapsar,Data Science,50000.0,45000
2,1003,Rohan Joshi,Chinchwad,Python Full Stack,30000.0,25000
3,1004,Sneha Kulkarni,NaN,Java Full Stack,NaN,20000
4,1005,Aditya More,Karve Nagar,Testing,25000.0,25000
6,1006,Neha Deshmukh,Hadapsar,Data Analytics,40000.0,35000
7,1007,Vikram Jadhav,Chinchwad,Data Science,50000.0,40000
8,1008,NaN,Nagpur,NaN,30000.0,28000
9,1008,Pooja Pawar,Nagpur,Python Full Stack,30000.0,28000
10,1009,Rahul Shinde,Karve Nagar,Java Full Stack,30000.0,22000
11,1010,Kavya Wagh,Hadapsar,Testing,25000.0,15000
12,1011,Siddhant Kale,Chinchwad,Data Analytics,40000.0,30000
13,1012,Anjali Bhosale,NaN,Data Science,50000.0,50000
14,1013,Omkar Pawar,Karve Nagar,Python Full Stack,NaN,20000
15,1014,Isha Suryawanshi,Hadapsar,Java Full Stack,30000.0,27000
16,1015,Kunal Patil,Chinchwad,NaN,25000.0,20000
17,1016,Riya Chavan,Nagpur,Data Analytics,40000.0,32000
19,1017,Akash Thakur,Karve Nagar,Data Science,50000.0,35000
20,1018,Mitali Gaikwad,Hadapsar,Python Full Stack,30000.0,30000
21,1019,Nikhil Salunkhe,Chinchwad,Java Full Stack,30000.0,18000
22,1020,Tanvi Nikam,Nagpur,Testing,NaN,22000
23,1021,Yashasvi Dalvi,Karve Nagar,Data Analytics,40000.0,22000