In [2]:
import pandas as pd

In [ ]:
'''series:
    one-diam  like column
'''

In [2]:
s1 = pd.Series([11,22,33,44,55])
s1

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [3]:
employee = {101:"vaibhav",102:"pranav",103:"pratik"}
s2 = pd.Series(employee)
print(s2)

101    vaibhav
102     pranav
103     pratik
dtype: str

In [19]:
marks = [67,89,45,67,34]
label = ['python','java','c','cpp','aws']
mk = pd.Series(marks,index = label)
print(mk)
print(mk.loc["java"])
print(mk.iloc[2])

python    67
java      89
c         45
cpp       67
aws       34
dtype: int64
89
45

In [6]:
marks = [67,89]
mk = pd.Series(marks,index = ["t1","t2"])
print(mk)

t1    67
t2    89
dtype: int64

In [8]:
marks = [67,89,78,89]
mk = pd.Series(marks,index = [f'T{i}' for i in range(1,len(marks)+1)])
print(mk)

T1    67
T2    89
T3    78
T4    89
dtype: int64

In [9]:
price = [1100,1200,1300]
p = pd.Series(price)
p -= p*10/100
p

0     990.0
1    1080.0
2    1170.0
dtype: float64

In [23]:
price = [1100,1200,1300]
p = pd.Series(price)
print(p.index)
print(p.values)
print(p.dtype)
print(p)

RangeIndex(start=0, stop=3, step=1)
[1100 1200 1300]
int64
0    1100
1    1200
2    1300
dtype: int64

In [7]:
emp = {
    "emp_id":[1,2,3,4],
    "emp_name":['raj','pavan','abhi','rahul'],
    "salary":[33000,66000,44000,55000]
}
df = pd.DataFrame(emp)
df

   emp_id emp_name  salary
0       1      raj   33000
1       2    pavan   66000
2       3     abhi   44000
3       4    rahul   55000

In [12]:
student = {
    "student_id":[101,102],
    "student_name":['yashasvi','diksha'],
    "fee":[10000,20000]
}
df = pd.DataFrame(student)
df

   student_id student_name    fee
0         101     yashasvi  10000
1         102       diksha  20000

In [27]:
products = {
    'pid' : [101,102,103],
    'pname': ['laptop','mobile','charger'],
    'mrp': [70000,30000,1200]
}
pdf = pd.DataFrame(products)
pdf = pd.DataFrame(products,index = products['pid'])
pdf

     pid    pname    mrp
101  101   laptop  70000
102  102   mobile  30000
103  103  charger   1200

In [28]:
pdf.iloc[0]
pdf.loc[102]

pid         102
pname    mobile
mrp       30000
Name: 102, dtype: object

In [29]:
pdf["pname"] 
pdf[["pname","mrp"]]

       pname    mrp
101   laptop  70000
102   mobile  30000
103  charger   1200

In [30]:
#add new column 
pdf["discount"] = [10,8,7]
pdf

     pid    pname    mrp  discount
101  101   laptop  70000        10
102  102   mobile  30000         8
103  103  charger   1200         7

In [31]:
pdf['discount amount'] = pdf['mrp']*pdf['discount']/100
pdf

     pid    pname    mrp  discount  discount amount
101  101   laptop  70000        10           7000.0
102  102   mobile  30000         8           2400.0
103  103  charger   1200         7             84.0

In [32]:
pdf["selling price" ] = pdf['mrp']-pdf['discount amount']
pdf

     pid    pname    mrp  discount  discount amount  selling price
101  101   laptop  70000        10           7000.0        63000.0
102  102   mobile  30000         8           2400.0        27600.0
103  103  charger   1200         7             84.0         1116.0

In [ ]:
#delete row 
pdf1 = pdf.drop(102)

In [36]:
pdf1

     pid    pname    mrp  discount  discount amount  selling price
101  101   laptop  70000        10           7000.0        63000.0
103  103  charger   1200         7             84.0         1116.0

In [37]:
pdf.drop(103,inplace = True)

In [38]:
pdf

     pid   pname    mrp  discount  discount amount  selling price
101  101  laptop  70000        10           7000.0        63000.0
102  102  mobile  30000         8           2400.0        27600.0

In [40]:
pdf.drop('pid',axis=1,inplace = True)

In [41]:
pdf

      pname    mrp  discount  discount amount  selling price
101  laptop  70000        10           7000.0        63000.0
102  mobile  30000         8           2400.0        27600.0

In [ ]:

'''
employee
empid label 
empname
department
basic_salary
access 103 record
access salary column

add new emp record
add new column HRA_amount - 10% of basic salary
add new column DA_amount - 8% of basic salary
add new coloumn salary - bs+hra+da
delete 104 record
delete department column
'''

In [18]:
employee = {
    "empid": [101,102,103,104,105],
    "empname": ["Siya","Shreya","Diksha","Aarya","Avni"],
    "department":["HR","IT","Finance","IT","Marketing"],
    "basic_salary":[50000,40000,70000,80000,60000],
}
df = pd.DataFrame(employee)
df

   empid empname department  basic_salary
0    101    Siya         HR         50000
1    102  Shreya         IT         40000
2    103  Diksha    Finance         70000
3    104   Aarya         IT         80000
4    105    Avni  Marketing         60000

In [ ]:
d = df[df["empid"]==103]
d

   empid empname department  basic_salary
2    103  Diksha    Finance         70000

In [ ]:
sal = pd.DataFrame(employee["basic_salary"])
sal

       0
0  50000
1  40000
2  70000
3  80000
4  60000

In [ ]:
new = pd.DataFrame(
    [
        {
            "empid":106,
            "empname":"Piya",
            "department":"Operation",
            "basic_salary":50000
        }
    ]
)
df = pd.concat([df,new],ignore_index=True)
df

   empid empname department  basic_salary
0    101    Siya         HR         50000
1    102  Shreya         IT         40000
2    103  Diksha    Finance         70000
3    104   Aarya         IT         80000
4    105    Avni  Marketing         60000
5    106    Piya  Operation         50000

In [ ]:
df["HRA_10_percent"] = df["basic_salary"] * 0.10
df["DA_8_percent"] = df["basic_salary"] * 0.08
df

   empid empname department  basic_salary  HRA_10_percent  DA_8_percent
0    101    Siya         HR         50000          5000.0        4000.0
1    102  Shreya         IT         40000          4000.0        3200.0
2    103  Diksha    Finance         70000          7000.0        5600.0
3    104   Aarya         IT         80000          8000.0        6400.0
4    105    Avni  Marketing         60000          6000.0        4800.0
5    106    Piya  Operation         50000          5000.0        4000.0

In [23]:
df["salary"] = df["basic_salary"]+df["HRA_10_percent"]+df["DA_8_percent"]
df

,empid,empname,department,basic_salary,HRA_10_percent,DA_8_percent,salary
0,101,Siya,HR,50000,5000.0,4000.0,59000.0
1,102,Shreya,IT,40000,4000.0,3200.0,47200.0
2,103,Diksha,Finance,70000,7000.0,5600.0,82600.0
3,104,Aarya,IT,80000,8000.0,6400.0,94400.0
4,105,Avni,Marketing,60000,6000.0,4800.0,70800.0
5,106,Piya,Operation,50000,5000.0,4000.0,59000.0

In [25]:
df = df[df["empid"] != 104].reset_index(drop=True)
df

,empid,empname,department,basic_salary,HRA_10_percent,DA_8_percent,salary
0,101,Siya,HR,50000,5000.0,4000.0,59000.0
1,102,Shreya,IT,40000,4000.0,3200.0,47200.0
2,103,Diksha,Finance,70000,7000.0,5600.0,82600.0
3,105,Avni,Marketing,60000,6000.0,4800.0,70800.0
4,106,Piya,Operation,50000,5000.0,4000.0,59000.0

In [26]:
df = df.drop(columns=["department"])
df

   empid empname  basic_salary  HRA_10_percent  DA_8_percent   salary
0    101    Siya         50000          5000.0        4000.0  59000.0
1    102  Shreya         40000          4000.0        3200.0  47200.0
2    103  Diksha         70000          7000.0        5600.0  82600.0
3    105    Avni         60000          6000.0        4800.0  70800.0
4    106    Piya         50000          5000.0        4000.0  59000.0