In [1]:
import pandas as pd

In [2]:
student_df = pd.read_excel("student_records_20.xlsx")
student_df

,student_id,name,branch,course,fees,paid_fees
0,1001,Aarav Sharma,Karve Nagar,Data Analytics,40000,30000
1,1002,Priya Patil,Hadapsar,Data Science,50000,45000
2,1003,Rohan Joshi,Chinchwad,Python Full Stack,30000,25000
3,1004,Sneha Kulkarni,Nagpur,Java Full Stack,30000,20000
4,1005,Aditya More,Karve Nagar,Testing,25000,25000
5,1006,Neha Deshmukh,Hadapsar,Data Analytics,40000,35000
6,1007,Vikram Jadhav,Chinchwad,Data Science,50000,40000
7,1008,Pooja Pawar,Nagpur,Python Full Stack,30000,28000
8,1009,Rahul Shinde,Karve Nagar,Java Full Stack,30000,22000
9,1010,Kavya Wagh,Hadapsar,Testing,25000,15000
10,1011,Siddhant Kale,Chinchwad,Data Analytics,40000,30000
11,1012,Anjali Bhosale,Nagpur,Data Science,50000,50000
12,1013,Omkar Pawar,Karve Nagar,Python Full Stack,30000,20000
13,1014,Isha Suryawanshi,Hadapsar,Java Full Stack,30000,27000
14,1015,Kunal Patil,Chinchwad,Testing,25000,20000
15,1016,Riya Chavan,Nagpur,Data Analytics,40000,32000
16,1017,Akash Thakur,Karve Nagar,Data Science,50000,35000
17,1018,Mitali Gaikwad,Hadapsar,Python Full Stack,30000,30000
18,1019,Nikhil Salunkhe,Chinchwad,Java Full Stack,30000,18000
19,1020,Tanvi Nikam,Nagpur,Testing,25000,22000

In [4]:
student_df.head()

,student_id,name,branch,course,fees,paid_fees
0,1001,Aarav Sharma,Karve Nagar,Data Analytics,40000,30000
1,1002,Priya Patil,Hadapsar,Data Science,50000,45000
2,1003,Rohan Joshi,Chinchwad,Python Full Stack,30000,25000
3,1004,Sneha Kulkarni,Nagpur,Java Full Stack,30000,20000
4,1005,Aditya More,Karve Nagar,Testing,25000,25000

In [5]:
student_df.tail()

,student_id,name,branch,course,fees,paid_fees
15,1016,Riya Chavan,Nagpur,Data Analytics,40000,32000
16,1017,Akash Thakur,Karve Nagar,Data Science,50000,35000
17,1018,Mitali Gaikwad,Hadapsar,Python Full Stack,30000,30000
18,1019,Nikhil Salunkhe,Chinchwad,Java Full Stack,30000,18000
19,1020,Tanvi Nikam,Nagpur,Testing,25000,22000

In [6]:
student_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  20 non-null     int64
 1   name        20 non-null     str
 2   branch      20 non-null     str
 3   course      20 non-null     str
 4   fees        20 non-null     int64
 5   paid_fees   20 non-null     int64
dtypes: int64(3), str(3)
memory usage: 1.1 KB

In [7]:
student_df.describe()

       student_id          fees     paid_fees
count    20.00000     20.000000     20.000000
mean   1010.50000  35000.000000  28450.000000
std       5.91608   9176.629355   9150.639897
min    1001.00000  25000.000000  15000.000000
25%    1005.75000  30000.000000  21500.000000
50%    1010.50000  30000.000000  27500.000000
75%    1015.25000  40000.000000  32750.000000
max    1020.00000  50000.000000  50000.000000

In [8]:
student_df.iloc[3]

student_id               1004
name           Sneha Kulkarni
branch                 Nagpur
course        Java Full Stack
fees                    30000
paid_fees               20000
Name: 3, dtype: object

In [9]:
student_df['name']

0         Aarav Sharma
1          Priya Patil
2          Rohan Joshi
3       Sneha Kulkarni
4          Aditya More
5        Neha Deshmukh
6        Vikram Jadhav
7          Pooja Pawar
8         Rahul Shinde
9           Kavya Wagh
10       Siddhant Kale
11      Anjali Bhosale
12         Omkar Pawar
13    Isha Suryawanshi
14         Kunal Patil
15         Riya Chavan
16        Akash Thakur
17      Mitali Gaikwad
18     Nikhil Salunkhe
19         Tanvi Nikam
Name: name, dtype: str

In [11]:
student_df[['name','paid_fees']]

                name  paid_fees
0       Aarav Sharma      30000
1        Priya Patil      45000
2        Rohan Joshi      25000
3     Sneha Kulkarni      20000
4        Aditya More      25000
5      Neha Deshmukh      35000
6      Vikram Jadhav      40000
7        Pooja Pawar      28000
8       Rahul Shinde      22000
9         Kavya Wagh      15000
10     Siddhant Kale      30000
11    Anjali Bhosale      50000
12       Omkar Pawar      20000
13  Isha Suryawanshi      27000
14       Kunal Patil      20000
15       Riya Chavan      32000
16      Akash Thakur      35000
17    Mitali Gaikwad      30000
18   Nikhil Salunkhe      18000
19       Tanvi Nikam      22000

In [3]:
student_df['remaining_fees'] = student_df['fees'] - student_df['paid_fees']

In [4]:
student_df

,student_id,name,branch,course,fees,paid_fees,remaining_fees
0,1001,Aarav Sharma,Karve Nagar,Data Analytics,40000,30000,10000
1,1002,Priya Patil,Hadapsar,Data Science,50000,45000,5000
2,1003,Rohan Joshi,Chinchwad,Python Full Stack,30000,25000,5000
3,1004,Sneha Kulkarni,Nagpur,Java Full Stack,30000,20000,10000
4,1005,Aditya More,Karve Nagar,Testing,25000,25000,0
5,1006,Neha Deshmukh,Hadapsar,Data Analytics,40000,35000,5000
6,1007,Vikram Jadhav,Chinchwad,Data Science,50000,40000,10000
7,1008,Pooja Pawar,Nagpur,Python Full Stack,30000,28000,2000
8,1009,Rahul Shinde,Karve Nagar,Java Full Stack,30000,22000,8000
9,1010,Kavya Wagh,Hadapsar,Testing,25000,15000,10000
10,1011,Siddhant Kale,Chinchwad,Data Analytics,40000,30000,10000
11,1012,Anjali Bhosale,Nagpur,Data Science,50000,50000,0
12,1013,Omkar Pawar,Karve Nagar,Python Full Stack,30000,20000,10000
13,1014,Isha Suryawanshi,Hadapsar,Java Full Stack,30000,27000,3000
14,1015,Kunal Patil,Chinchwad,Testing,25000,20000,5000
15,1016,Riya Chavan,Nagpur,Data Analytics,40000,32000,8000
16,1017,Akash Thakur,Karve Nagar,Data Science,50000,35000,15000
17,1018,Mitali Gaikwad,Hadapsar,Python Full Stack,30000,30000,0
18,1019,Nikhil Salunkhe,Chinchwad,Java Full Stack,30000,18000,12000
19,1020,Tanvi Nikam,Nagpur,Testing,25000,22000,3000

In [ ]:
#drop row
student_df.drop(19)

,student_id,name,branch,course,fees,paid_fees,remaining_fees
0,1001,Aarav Sharma,Karve Nagar,Data Analytics,40000,30000,10000
1,1002,Priya Patil,Hadapsar,Data Science,50000,45000,5000
2,1003,Rohan Joshi,Chinchwad,Python Full Stack,30000,25000,5000
3,1004,Sneha Kulkarni,Nagpur,Java Full Stack,30000,20000,10000
4,1005,Aditya More,Karve Nagar,Testing,25000,25000,0
5,1006,Neha Deshmukh,Hadapsar,Data Analytics,40000,35000,5000
6,1007,Vikram Jadhav,Chinchwad,Data Science,50000,40000,10000
7,1008,Pooja Pawar,Nagpur,Python Full Stack,30000,28000,2000
8,1009,Rahul Shinde,Karve Nagar,Java Full Stack,30000,22000,8000
9,1010,Kavya Wagh,Hadapsar,Testing,25000,15000,10000
10,1011,Siddhant Kale,Chinchwad,Data Analytics,40000,30000,10000
11,1012,Anjali Bhosale,Nagpur,Data Science,50000,50000,0
12,1013,Omkar Pawar,Karve Nagar,Python Full Stack,30000,20000,10000
13,1014,Isha Suryawanshi,Hadapsar,Java Full Stack,30000,27000,3000
14,1015,Kunal Patil,Chinchwad,Testing,25000,20000,5000
15,1016,Riya Chavan,Nagpur,Data Analytics,40000,32000,8000
16,1017,Akash Thakur,Karve Nagar,Data Science,50000,35000,15000
17,1018,Mitali Gaikwad,Hadapsar,Python Full Stack,30000,30000,0
18,1019,Nikhil Salunkhe,Chinchwad,Java Full Stack,30000,18000,12000

In [ ]:
#drop column 
student_df.drop('student_id',axis=1)

,name,branch,course,fees,paid_fees,remaining_fees
0,Aarav Sharma,Karve Nagar,Data Analytics,40000,30000,10000
1,Priya Patil,Hadapsar,Data Science,50000,45000,5000
2,Rohan Joshi,Chinchwad,Python Full Stack,30000,25000,5000
3,Sneha Kulkarni,Nagpur,Java Full Stack,30000,20000,10000
4,Aditya More,Karve Nagar,Testing,25000,25000,0
5,Neha Deshmukh,Hadapsar,Data Analytics,40000,35000,5000
6,Vikram Jadhav,Chinchwad,Data Science,50000,40000,10000
7,Pooja Pawar,Nagpur,Python Full Stack,30000,28000,2000
8,Rahul Shinde,Karve Nagar,Java Full Stack,30000,22000,8000
9,Kavya Wagh,Hadapsar,Testing,25000,15000,10000
10,Siddhant Kale,Chinchwad,Data Analytics,40000,30000,10000
11,Anjali Bhosale,Nagpur,Data Science,50000,50000,0
12,Omkar Pawar,Karve Nagar,Python Full Stack,30000,20000,10000
13,Isha Suryawanshi,Hadapsar,Java Full Stack,30000,27000,3000
14,Kunal Patil,Chinchwad,Testing,25000,20000,5000
15,Riya Chavan,Nagpur,Data Analytics,40000,32000,8000
16,Akash Thakur,Karve Nagar,Data Science,50000,35000,15000
17,Mitali Gaikwad,Hadapsar,Python Full Stack,30000,30000,0
18,Nikhil Salunkhe,Chinchwad,Java Full Stack,30000,18000,12000
19,Tanvi Nikam,Nagpur,Testing,25000,22000,3000

In [18]:
student_df[student_df["course"] == "Data Analytics"]

    student_id           name       branch          course   fees  paid_fees
0         1001   Aarav Sharma  Karve Nagar  Data Analytics  40000      30000
5         1006  Neha Deshmukh     Hadapsar  Data Analytics  40000      35000
10        1011  Siddhant Kale    Chinchwad  Data Analytics  40000      30000
15        1016    Riya Chavan       Nagpur  Data Analytics  40000      32000

In [9]:
Python_Full_Stack_df = student_df[student_df["course"]== "Python Full Stack"]

In [10]:
Python_Full_Stack_df

,student_id,name,branch,course,fees,paid_fees,remaining_fees
2,1003,Rohan Joshi,Chinchwad,Python Full Stack,30000,25000,5000
7,1008,Pooja Pawar,Nagpur,Python Full Stack,30000,28000,2000
12,1013,Omkar Pawar,Karve Nagar,Python Full Stack,30000,20000,10000
17,1018,Mitali Gaikwad,Hadapsar,Python Full Stack,30000,30000,0

In [11]:
Python_full_stack_df = student_df[student_df["course"]=="Python Full Stack"]
Data_Analytics_df = student_df[student_df["course"] == "Data Analytics"]

In [12]:
Data_Analytics_df

,student_id,name,branch,course,fees,paid_fees,remaining_fees
0,1001,Aarav Sharma,Karve Nagar,Data Analytics,40000,30000,10000
5,1006,Neha Deshmukh,Hadapsar,Data Analytics,40000,35000,5000
10,1011,Siddhant Kale,Chinchwad,Data Analytics,40000,30000,10000
15,1016,Riya Chavan,Nagpur,Data Analytics,40000,32000,8000

In [16]:
student_df

,student_id,name,branch,course,fees,paid_fees
0,1001,Aarav Sharma,Karve Nagar,Data Analytics,40000,30000
1,1002,Priya Patil,Hadapsar,Data Science,50000,45000
2,1003,Rohan Joshi,Chinchwad,Python Full Stack,30000,25000
3,1004,Sneha Kulkarni,Nagpur,Java Full Stack,30000,20000
4,1005,Aditya More,Karve Nagar,Testing,25000,25000
5,1006,Neha Deshmukh,Hadapsar,Data Analytics,40000,35000
6,1007,Vikram Jadhav,Chinchwad,Data Science,50000,40000
7,1008,Pooja Pawar,Nagpur,Python Full Stack,30000,28000
8,1009,Rahul Shinde,Karve Nagar,Java Full Stack,30000,22000
9,1010,Kavya Wagh,Hadapsar,Testing,25000,15000
10,1011,Siddhant Kale,Chinchwad,Data Analytics,40000,30000
11,1012,Anjali Bhosale,Nagpur,Data Science,50000,50000
12,1013,Omkar Pawar,Karve Nagar,Python Full Stack,30000,20000
13,1014,Isha Suryawanshi,Hadapsar,Java Full Stack,30000,27000
14,1015,Kunal Patil,Chinchwad,Testing,25000,20000
15,1016,Riya Chavan,Nagpur,Data Analytics,40000,32000
16,1017,Akash Thakur,Karve Nagar,Data Science,50000,35000
17,1018,Mitali Gaikwad,Hadapsar,Python Full Stack,30000,30000
18,1019,Nikhil Salunkhe,Chinchwad,Java Full Stack,30000,18000
19,1020,Tanvi Nikam,Nagpur,Testing,25000,22000

In [13]:
student_df[student_df["remaining_fees"]==0]

,student_id,name,branch,course,fees,paid_fees,remaining_fees
4,1005,Aditya More,Karve Nagar,Testing,25000,25000,0
11,1012,Anjali Bhosale,Nagpur,Data Science,50000,50000,0
17,1018,Mitali Gaikwad,Hadapsar,Python Full Stack,30000,30000,0

In [14]:
student_df[student_df["branch"] == "Karve Nagar"]

,student_id,name,branch,course,fees,paid_fees,remaining_fees
0,1001,Aarav Sharma,Karve Nagar,Data Analytics,40000,30000,10000
4,1005,Aditya More,Karve Nagar,Testing,25000,25000,0
8,1009,Rahul Shinde,Karve Nagar,Java Full Stack,30000,22000,8000
12,1013,Omkar Pawar,Karve Nagar,Python Full Stack,30000,20000,10000
16,1017,Akash Thakur,Karve Nagar,Data Science,50000,35000,15000

In [16]:
student_df[(student_df["course"]=="Data Science")& (student_df["remaining_fees"] == 0)]

,student_id,name,branch,course,fees,paid_fees,remaining_fees
11,1012,Anjali Bhosale,Nagpur,Data Science,50000,50000,0

In [17]:
student_df[(student_df["branch"] =="Karve Nagar") & (student_df["course"]=="Data Science")]

,student_id,name,branch,course,fees,paid_fees,remaining_fees
16,1017,Akash Thakur,Karve Nagar,Data Science,50000,35000,15000

In [18]:
student_df[(student_df["course"]=="Data Analytics")|(student_df["course"]=="Data Science")]

,student_id,name,branch,course,fees,paid_fees,remaining_fees
0,1001,Aarav Sharma,Karve Nagar,Data Analytics,40000,30000,10000
1,1002,Priya Patil,Hadapsar,Data Science,50000,45000,5000
5,1006,Neha Deshmukh,Hadapsar,Data Analytics,40000,35000,5000
6,1007,Vikram Jadhav,Chinchwad,Data Science,50000,40000,10000
10,1011,Siddhant Kale,Chinchwad,Data Analytics,40000,30000,10000
11,1012,Anjali Bhosale,Nagpur,Data Science,50000,50000,0
15,1016,Riya Chavan,Nagpur,Data Analytics,40000,32000,8000
16,1017,Akash Thakur,Karve Nagar,Data Science,50000,35000,15000

In [20]:
student_df[((student_df["course"]=="Data Analytics")|(student_df["course"]=="Data Science")) & (student_df["remaining_fees"]>5000)]

,student_id,name,branch,course,fees,paid_fees,remaining_fees
0,1001,Aarav Sharma,Karve Nagar,Data Analytics,40000,30000,10000
6,1007,Vikram Jadhav,Chinchwad,Data Science,50000,40000,10000
10,1011,Siddhant Kale,Chinchwad,Data Analytics,40000,30000,10000
15,1016,Riya Chavan,Nagpur,Data Analytics,40000,32000,8000
16,1017,Akash Thakur,Karve Nagar,Data Science,50000,35000,15000

In [ ]:
#sort
student_df.sort_values(by="remaining_fees",ascending=False)
student_df.sort_values(by="remaining_fees")

,student_id,name,branch,course,fees,paid_fees,remaining_fees
4,1005,Aditya More,Karve Nagar,Testing,25000,25000,0
11,1012,Anjali Bhosale,Nagpur,Data Science,50000,50000,0
17,1018,Mitali Gaikwad,Hadapsar,Python Full Stack,30000,30000,0
7,1008,Pooja Pawar,Nagpur,Python Full Stack,30000,28000,2000
19,1020,Tanvi Nikam,Nagpur,Testing,25000,22000,3000
13,1014,Isha Suryawanshi,Hadapsar,Java Full Stack,30000,27000,3000
5,1006,Neha Deshmukh,Hadapsar,Data Analytics,40000,35000,5000
14,1015,Kunal Patil,Chinchwad,Testing,25000,20000,5000
1,1002,Priya Patil,Hadapsar,Data Science,50000,45000,5000
2,1003,Rohan Joshi,Chinchwad,Python Full Stack,30000,25000,5000
15,1016,Riya Chavan,Nagpur,Data Analytics,40000,32000,8000
8,1009,Rahul Shinde,Karve Nagar,Java Full Stack,30000,22000,8000
6,1007,Vikram Jadhav,Chinchwad,Data Science,50000,40000,10000
9,1010,Kavya Wagh,Hadapsar,Testing,25000,15000,10000
0,1001,Aarav Sharma,Karve Nagar,Data Analytics,40000,30000,10000
3,1004,Sneha Kulkarni,Nagpur,Java Full Stack,30000,20000,10000
12,1013,Omkar Pawar,Karve Nagar,Python Full Stack,30000,20000,10000
10,1011,Siddhant Kale,Chinchwad,Data Analytics,40000,30000,10000
18,1019,Nikhil Salunkhe,Chinchwad,Java Full Stack,30000,18000,12000
16,1017,Akash Thakur,Karve Nagar,Data Science,50000,35000,15000