In [77]:
import pandas as pd

In [78]:
product_df = pd.read_csv("product_records_20.csv")
product_df.head()

   pid           pname     caterory  quantity  cost_price_per_unit    mrp
0    1          Laptop  Electronics        10                45000  55000
1    2  Wireless Mouse  Accessories        35                  500    800
2    3        Keyboard  Accessories        25                  900   1400
3    4         Monitor  Electronics        12                 9000  12000
4    5      Headphones        Audio        20                 1200   1800

In [79]:
product_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   pid                  20 non-null     int64
 1   pname                20 non-null     str
 2   caterory             20 non-null     str
 3   quantity             20 non-null     int64
 4   cost_price_per_unit  20 non-null     int64
 5   mrp                  20 non-null     int64
dtypes: int64(4), str(2)
memory usage: 1.1 KB

In [80]:
product_df.isnull().sum()

pid                    0
pname                  0
caterory               0
quantity               0
cost_price_per_unit    0
mrp                    0
dtype: int64

In [81]:
product_df.columns

Index(['pid', 'pname', 'caterory', 'quantity', 'cost_price_per_unit', 'mrp'], dtype='str')

In [82]:
len(product_df['caterory'].unique())
# product_df['caterory'].unique()

7

In [83]:
product_df['profit'] = product_df["mrp"]-product_df["cost_price_per_unit"]
product_df

,pid,pname,caterory,quantity,cost_price_per_unit,mrp,profit
0,1,Laptop,Electronics,10,45000,55000,10000
1,2,Wireless Mouse,Accessories,35,500,800,300
2,3,Keyboard,Accessories,25,900,1400,500
3,4,Monitor,Electronics,12,9000,12000,3000
4,5,Headphones,Audio,20,1200,1800,600
5,6,USB Cable,Accessories,50,150,300,150
6,7,Power Bank,Electronics,18,900,1400,500
7,8,Webcam,Electronics,15,1800,2600,800
8,9,Bluetooth Speaker,Audio,14,2200,3200,1000
9,10,Smart Watch,Wearables,16,2500,3800,1300
10,11,Mobile Stand,Accessories,30,250,450,200
11,12,Tablet,Electronics,8,18000,24000,6000
12,13,Power Adapter,Accessories,22,700,1100,400
13,14,Earbuds,Audio,25,1500,2200,700
14,15,Laptop Bag,Bags,18,1000,1600,600
15,16,External SSD,Storage,10,5500,7500,2000
16,17,Pen Drive,Storage,40,450,700,250
17,18,Router,Networking,13,1800,2800,1000
18,19,Mechanical Keyboard,Accessories,9,2800,4000,1200
19,20,Gaming Mouse,Accessories,17,1600,2400,800

In [84]:
# total_qnt = product_df["quantity"].sum()
# total_qnt
# total_cost = product_df["cost_price_per_unit"].sum()
# total_cost
total_profit = product_df['profit'].sum()
total_profit

np.int64(31300)

In [85]:
# total_orders = product_df['pid'].count()
# total_orders
# avg_profit = product_df['profit'].mean()
# avg_profit
av_cost = product_df['cost_price_per_unit'].mean()
av_cost

np.float64(4887.5)

In [86]:
gp = product_df.groupby(by="caterory")
gp

In [87]:
gp["profit"].sum()

caterory
Accessories     3550
Audio           2300
Bags             600
Electronics    20300
Networking      1000
Storage         2250
Wearables       1300
Name: profit, dtype: int64

In [88]:
gp["quantity"].sum()

caterory
Accessories    188
Audio           59
Bags            18
Electronics     63
Networking      13
Storage         50
Wearables       16
Name: quantity, dtype: int64

In [89]:
pdetails = pd.read_csv("product_details.csv")
pdetails

   product_id product_name    mrp  quantity
0         101       laptop  70000       100
1         104          fan   3000        40
2         105           Tv  30000        80

In [90]:
pasales = pd.read_csv("product_sales.csv")
pasales

   product_id  quantity
0         101       100
1         103       200
2         104        40
3         105        80
4         106       199

In [91]:
pd.merge(pdetails,pasales, how = 'inner',on='product_id')

   product_id product_name    mrp  quantity_x  quantity_y
0         101       laptop  70000         100         100
1         104          fan   3000          40          40
2         105           Tv  30000          80          80

In [92]:
pd.merge(pdetails,pasales, how = 'left',on='product_id')

   product_id product_name    mrp  quantity_x  quantity_y
0         101       laptop  70000         100         100
1         104          fan   3000          40          40
2         105           Tv  30000          80          80

In [93]:
pd.merge(pdetails,pasales, how = 'right',on='product_id')

   product_id product_name      mrp  quantity_x  quantity_y
0         101       laptop  70000.0       100.0         100
1         103          NaN      NaN         NaN         200
2         104          fan   3000.0        40.0          40
3         105           Tv  30000.0        80.0          80
4         106          NaN      NaN         NaN         199

In [94]:
product_df

,pid,pname,caterory,quantity,cost_price_per_unit,mrp,profit
0,1,Laptop,Electronics,10,45000,55000,10000
1,2,Wireless Mouse,Accessories,35,500,800,300
2,3,Keyboard,Accessories,25,900,1400,500
3,4,Monitor,Electronics,12,9000,12000,3000
4,5,Headphones,Audio,20,1200,1800,600
5,6,USB Cable,Accessories,50,150,300,150
6,7,Power Bank,Electronics,18,900,1400,500
7,8,Webcam,Electronics,15,1800,2600,800
8,9,Bluetooth Speaker,Audio,14,2200,3200,1000
9,10,Smart Watch,Wearables,16,2500,3800,1300
10,11,Mobile Stand,Accessories,30,250,450,200
11,12,Tablet,Electronics,8,18000,24000,6000
12,13,Power Adapter,Accessories,22,700,1100,400
13,14,Earbuds,Audio,25,1500,2200,700
14,15,Laptop Bag,Bags,18,1000,1600,600
15,16,External SSD,Storage,10,5500,7500,2000
16,17,Pen Drive,Storage,40,450,700,250
17,18,Router,Networking,13,1800,2800,1000
18,19,Mechanical Keyboard,Accessories,9,2800,4000,1200
19,20,Gaming Mouse,Accessories,17,1600,2400,800

In [95]:
product_df.loc[len(product_df)] = [21,"mobile","Electronics",10,20000,30000,10000]

In [96]:
product_df

,pid,pname,caterory,quantity,cost_price_per_unit,mrp,profit
0,1,Laptop,Electronics,10,45000,55000,10000
1,2,Wireless Mouse,Accessories,35,500,800,300
2,3,Keyboard,Accessories,25,900,1400,500
3,4,Monitor,Electronics,12,9000,12000,3000
4,5,Headphones,Audio,20,1200,1800,600
5,6,USB Cable,Accessories,50,150,300,150
6,7,Power Bank,Electronics,18,900,1400,500
7,8,Webcam,Electronics,15,1800,2600,800
8,9,Bluetooth Speaker,Audio,14,2200,3200,1000
9,10,Smart Watch,Wearables,16,2500,3800,1300
10,11,Mobile Stand,Accessories,30,250,450,200
11,12,Tablet,Electronics,8,18000,24000,6000
12,13,Power Adapter,Accessories,22,700,1100,400
13,14,Earbuds,Audio,25,1500,2200,700
14,15,Laptop Bag,Bags,18,1000,1600,600
15,16,External SSD,Storage,10,5500,7500,2000
16,17,Pen Drive,Storage,40,450,700,250
17,18,Router,Networking,13,1800,2800,1000
18,19,Mechanical Keyboard,Accessories,9,2800,4000,1200
19,20,Gaming Mouse,Accessories,17,1600,2400,800
20,21,mobile,Electronics,10,20000,30000,10000

In [100]:
data = {'pid':[22],'pname':["fan"],'caterory':["Electronics"],'quantity':[10],'cost_price_per_unit':[2000],'mrp':[3000],'profit':[1000]}
data_df = pd.DataFrame(data)
print(data_df)
pd.concat([product_df,data_df])

   pid pname     caterory  quantity  cost_price_per_unit   mrp  profit
0   22   fan  Electronics        10                 2000  3000    1000

,pid,pname,caterory,quantity,cost_price_per_unit,mrp,profit
0,1,Laptop,Electronics,10,45000,55000,10000
1,2,Wireless Mouse,Accessories,35,500,800,300
2,3,Keyboard,Accessories,25,900,1400,500
3,4,Monitor,Electronics,12,9000,12000,3000
4,5,Headphones,Audio,20,1200,1800,600
5,6,USB Cable,Accessories,50,150,300,150
6,7,Power Bank,Electronics,18,900,1400,500
7,8,Webcam,Electronics,15,1800,2600,800
8,9,Bluetooth Speaker,Audio,14,2200,3200,1000
9,10,Smart Watch,Wearables,16,2500,3800,1300
10,11,Mobile Stand,Accessories,30,250,450,200
11,12,Tablet,Electronics,8,18000,24000,6000
12,13,Power Adapter,Accessories,22,700,1100,400
13,14,Earbuds,Audio,25,1500,2200,700
14,15,Laptop Bag,Bags,18,1000,1600,600
15,16,External SSD,Storage,10,5500,7500,2000
16,17,Pen Drive,Storage,40,450,700,250
17,18,Router,Networking,13,1800,2800,1000
18,19,Mechanical Keyboard,Accessories,9,2800,4000,1200
19,20,Gaming Mouse,Accessories,17,1600,2400,800
20,21,mobile,Electronics,10,20000,30000,10000
0,22,fan,Electronics,10,2000,3000,1000

In [101]:
product_df.to_excel("mydata.xlsx",index=False)