In [1]:
import pandas as pd

In [2]:
emp_data = {
    'emp_id':[101,102,103,104],
    'Gender':["Male","Female","Female","Male"],
    "Department":["HR","Placement","HR","Placement"],
    "Rating":['Avg','Good','Bad','Very Good']
}
emp_df = pd.DataFrame(emp_data)
emp_df

   emp_id  Gender Department     Rating
0     101    Male         HR        Avg
1     102  Female  Placement       Good
2     103  Female         HR        Bad
3     104    Male  Placement  Very Good

In [7]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
emp_df["Gender"]=label.fit_transform(emp_df[["Gender"]])
emp_df

c:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

   emp_id  Gender Department     Rating
0     101       1         HR        Avg
1     102       0  Placement       Good
2     103       0         HR        Bad
3     104       1  Placement  Very Good

In [9]:
from sklearn.preprocessing import OrdinalEncoder
ordinal = OrdinalEncoder(categories=[['Avg','Good','Bad','Very Good']])
ordinal.fit_transform(emp_df[["Rating"]])

array([[0.],
       [1.],
       [2.],
       [3.]])

In [ ]:
pd.get_dummies(emp_df,columns=)