In [1]:
import pandas as pd
from sklearn.cluster import DBSCAN

data = {
    "Point":["A","B","C","D","E","F","G","H","I","J"],
    "X":[1,1,2,2,3,8,8,9,9,20],
    "Y":[1,2,1,2,2,8,9,8,9,20]
}
df = pd.DataFrame(data)
df

  Point   X   Y
0     A   1   1
1     B   1   2
2     C   2   1
3     D   2   2
4     E   3   2
5     F   8   8
6     G   8   9
7     H   9   8
8     I   9   9
9     J  20  20

In [2]:
x = df[["X","Y"]]
model = DBSCAN(
    eps = 1.5,min_samples=4
)
df["Cluster"] = model.fit_predict(x)
df

  Point   X   Y  Cluster
0     A   1   1        0
1     B   1   2        0
2     C   2   1        0
3     D   2   2        0
4     E   3   2        0
5     F   8   8        1
6     G   8   9        1
7     H   9   8        1
8     I   9   9        1
9     J  20  20       -1