In [7]:
import pandas as pd
from sklearn.cluster import KMeans
data = {
    'student_name':["Amit","Rahul","Sneha","Priya","Ruchi","Neha"],
    "Attendance":[95,90,85,70,60,55],
    "Marks":[88,82,78,65,55,48]
}
df = pd.DataFrame(data)
df

  student_name  Attendance  Marks
0         Amit          95     88
1        Rahul          90     82
2        Sneha          85     78
3        Priya          70     65
4        Ruchi          60     55
5         Neha          55     48

In [8]:
x = df[["Attendance","Marks"]]

In [10]:
model = KMeans(n_clusters=2,random_state=42,n_init=10)
df["Cluster"] = model.fit_predict(x)
df

  student_name  Attendance  Marks  Cluster
0         Amit          95     88        0
1        Rahul          90     82        0
2        Sneha          85     78        0
3        Priya          70     65        1
4        Ruchi          60     55        1
5         Neha          55     48        1

In [11]:
print("\nCentroids:")
print(model.cluster_centers_)

Centroids:
[[90.         82.66666667]
 [61.66666667 56.        ]]

In [12]:
df

  student_name  Attendance  Marks  Cluster
0         Amit          95     88        0
1        Rahul          90     82        0
2        Sneha          85     78        0
3        Priya          70     65        1
4        Ruchi          60     55        1
5         Neha          55     48        1