In [1]:
import pandas as pd

In [2]:
student_df = pd.read_excel("student_data.xlsx")
student_df

,student_id,name,age,gender,city,course,joining_date,study_hours,attendance,marks,fees_paid,fees_total
0,101,Rahul,22,Male,Pune,Data Science,2025-01-15,5,85,78,35000,40000
1,102,Priya,21,Female,Mumbai,Data Analytics,2025-02-10,3,72,65,30000,40000
2,103,Amit,24,Male,Pune,Data Science,2025-01-20,7,91,88,40000,40000
3,104,Sneha,23,Female,Nashik,Python,2025-03-05,2,60,55,20000,30000
4,105,Karan,25,Male,Mumbai,Data Analytics,2025-01-25,6,95,92,35000,40000
5,106,Neha,22,Female,Pune,Python,2025-02-18,4,78,70,25000,30000
6,107,Rohit,27,Male,Nagpur,Data Science,2025-03-12,1,55,45,15000,40000
7,108,Pooja,21,Female,Nashik,Data Analytics,2025-02-22,8,97,95,40000,40000
8,109,Vikram,26,Male,Pune,Python,2025-01-30,3,68,60,22000,30000
9,110,Anjali,23,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000
10,111,ajay,67,Male,Pune,Python,2025-01-30,3,68,60,22000,30000
11,112,suraj,45,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000
12,113,vijay,72,Male,Pune,Python,2025-01-30,3,68,60,22000,30000
13,114,kunal,56,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000

In [4]:
bins = [0,25,60,100]
lb = ["young","adult","Senior"]
student_df['age_gp']=pd.cut(student_df['age'],bins=bins,labels=lb)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
or_encoder = OrdinalEncoder(categories=[['young','adult','Senior']])
student_df['age_gp'] = or_encoder.fit_transform(student_df[['age_gp']])

In [8]:
student_df

,student_id,name,age,gender,city,course,joining_date,study_hours,attendance,marks,fees_paid,fees_total,age_gp
0,101,Rahul,22,Male,Pune,Data Science,2025-01-15,5,85,78,35000,40000,0.0
1,102,Priya,21,Female,Mumbai,Data Analytics,2025-02-10,3,72,65,30000,40000,0.0
2,103,Amit,24,Male,Pune,Data Science,2025-01-20,7,91,88,40000,40000,0.0
3,104,Sneha,23,Female,Nashik,Python,2025-03-05,2,60,55,20000,30000,0.0
4,105,Karan,25,Male,Mumbai,Data Analytics,2025-01-25,6,95,92,35000,40000,0.0
5,106,Neha,22,Female,Pune,Python,2025-02-18,4,78,70,25000,30000,0.0
6,107,Rohit,27,Male,Nagpur,Data Science,2025-03-12,1,55,45,15000,40000,1.0
7,108,Pooja,21,Female,Nashik,Data Analytics,2025-02-22,8,97,95,40000,40000,0.0
8,109,Vikram,26,Male,Pune,Python,2025-01-30,3,68,60,22000,30000,1.0
9,110,Anjali,23,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,0.0
10,111,ajay,67,Male,Pune,Python,2025-01-30,3,68,60,22000,30000,2.0
11,112,suraj,45,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,1.0
12,113,vijay,72,Male,Pune,Python,2025-01-30,3,68,60,22000,30000,2.0
13,114,kunal,56,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,1.0