In [1]:
import pandas as pd

In [2]:
student_df = pd.read_excel("student_data.xlsx")
student_df

,student_id,name,age,gender,city,course,joining_date,study_hours,attendance,marks,fees_paid,fees_total
0,101,Rahul,22,Male,Pune,Data Science,2025-01-15,5,85,78,35000,40000
1,102,Priya,21,Female,Mumbai,Data Analytics,2025-02-10,3,72,65,30000,40000
2,103,Amit,24,Male,Pune,Data Science,2025-01-20,7,91,88,40000,40000
3,104,Sneha,23,Female,Nashik,Python,2025-03-05,2,60,55,20000,30000
4,105,Karan,25,Male,Mumbai,Data Analytics,2025-01-25,6,95,92,35000,40000
5,106,Neha,22,Female,Pune,Python,2025-02-18,4,78,70,25000,30000
6,107,Rohit,27,Male,Nagpur,Data Science,2025-03-12,1,55,45,15000,40000
7,108,Pooja,21,Female,Nashik,Data Analytics,2025-02-22,8,97,95,40000,40000
8,109,Vikram,26,Male,Pune,Python,2025-01-30,3,68,60,22000,30000
9,110,Anjali,23,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000

In [3]:
student_df['remaining_fees'] = student_df['fees_total']-student_df['fees_paid']

In [4]:
student_df

,student_id,name,age,gender,city,course,joining_date,study_hours,attendance,marks,fees_paid,fees_total,remaining_fees
0,101,Rahul,22,Male,Pune,Data Science,2025-01-15,5,85,78,35000,40000,5000
1,102,Priya,21,Female,Mumbai,Data Analytics,2025-02-10,3,72,65,30000,40000,10000
2,103,Amit,24,Male,Pune,Data Science,2025-01-20,7,91,88,40000,40000,0
3,104,Sneha,23,Female,Nashik,Python,2025-03-05,2,60,55,20000,30000,10000
4,105,Karan,25,Male,Mumbai,Data Analytics,2025-01-25,6,95,92,35000,40000,5000
5,106,Neha,22,Female,Pune,Python,2025-02-18,4,78,70,25000,30000,5000
6,107,Rohit,27,Male,Nagpur,Data Science,2025-03-12,1,55,45,15000,40000,25000
7,108,Pooja,21,Female,Nashik,Data Analytics,2025-02-22,8,97,95,40000,40000,0
8,109,Vikram,26,Male,Pune,Python,2025-01-30,3,68,60,22000,30000,8000
9,110,Anjali,23,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,10000

In [8]:
def student_performance(marks):
    if marks>=80:
        return "Excellent"
    elif marks>=60:
        return "Good"
    else:
        return "Poor"
per = student_df['marks'].apply(student_performance)
student_df['performance'] = per
student_df

,student_id,name,age,gender,city,course,joining_date,study_hours,attendance,marks,fees_paid,fees_total,remaining_fees,performance
0,101,Rahul,22,Male,Pune,Data Science,2025-01-15,5,85,78,35000,40000,5000,Good
1,102,Priya,21,Female,Mumbai,Data Analytics,2025-02-10,3,72,65,30000,40000,10000,Good
2,103,Amit,24,Male,Pune,Data Science,2025-01-20,7,91,88,40000,40000,0,Excellent
3,104,Sneha,23,Female,Nashik,Python,2025-03-05,2,60,55,20000,30000,10000,Poor
4,105,Karan,25,Male,Mumbai,Data Analytics,2025-01-25,6,95,92,35000,40000,5000,Excellent
5,106,Neha,22,Female,Pune,Python,2025-02-18,4,78,70,25000,30000,5000,Good
6,107,Rohit,27,Male,Nagpur,Data Science,2025-03-12,1,55,45,15000,40000,25000,Poor
7,108,Pooja,21,Female,Nashik,Data Analytics,2025-02-22,8,97,95,40000,40000,0,Excellent
8,109,Vikram,26,Male,Pune,Python,2025-01-30,3,68,60,22000,30000,8000,Good
9,110,Anjali,23,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,10000,Excellent

In [15]:
student_df['year'] = student_df['joining_date'].dt.year

In [16]:
student_df

,student_id,name,age,gender,city,course,joining_date,study_hours,attendance,marks,fees_paid,fees_total,remaining_fees,performance,year
0,101,Rahul,22,Male,Pune,Data Science,2025-01-15,5,85,78,35000,40000,5000,Good,2025
1,102,Priya,21,Female,Mumbai,Data Analytics,2025-02-10,3,72,65,30000,40000,10000,Good,2025
2,103,Amit,24,Male,Pune,Data Science,2025-01-20,7,91,88,40000,40000,0,Excellent,2025
3,104,Sneha,23,Female,Nashik,Python,2025-03-05,2,60,55,20000,30000,10000,Poor,2025
4,105,Karan,25,Male,Mumbai,Data Analytics,2025-01-25,6,95,92,35000,40000,5000,Excellent,2025
5,106,Neha,22,Female,Pune,Python,2025-02-18,4,78,70,25000,30000,5000,Good,2025
6,107,Rohit,27,Male,Nagpur,Data Science,2025-03-12,1,55,45,15000,40000,25000,Poor,2025
7,108,Pooja,21,Female,Nashik,Data Analytics,2025-02-22,8,97,95,40000,40000,0,Excellent,2025
8,109,Vikram,26,Male,Pune,Python,2025-01-30,3,68,60,22000,30000,8000,Good,2025
9,110,Anjali,23,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,10000,Excellent,2025

In [19]:
from sklearn.preprocessing import LabelEncoder
label_en = LabelEncoder()
student_df['gender'] = label_en.fit_transform(student_df['gender'])

In [22]:
student_df['gender'] = label_en.fit_transform(student_df['gender'])
student_df = pd.get_dummies(student_df,columns = ['course'])
student_df

,student_id,name,age,gender,city,joining_date,study_hours,attendance,marks,fees_paid,fees_total,remaining_fees,performance,year,course_Data Analytics,course_Data Science,course_Python
0,101,Rahul,22,1,Pune,2025-01-15,5,85,78,35000,40000,5000,Good,2025,False,True,False
1,102,Priya,21,0,Mumbai,2025-02-10,3,72,65,30000,40000,10000,Good,2025,True,False,False
2,103,Amit,24,1,Pune,2025-01-20,7,91,88,40000,40000,0,Excellent,2025,False,True,False
3,104,Sneha,23,0,Nashik,2025-03-05,2,60,55,20000,30000,10000,Poor,2025,False,False,True
4,105,Karan,25,1,Mumbai,2025-01-25,6,95,92,35000,40000,5000,Excellent,2025,True,False,False
5,106,Neha,22,0,Pune,2025-02-18,4,78,70,25000,30000,5000,Good,2025,False,False,True
6,107,Rohit,27,1,Nagpur,2025-03-12,1,55,45,15000,40000,25000,Poor,2025,False,True,False
7,108,Pooja,21,0,Nashik,2025-02-22,8,97,95,40000,40000,0,Excellent,2025,True,False,False
8,109,Vikram,26,1,Pune,2025-01-30,3,68,60,22000,30000,8000,Good,2025,False,False,True
9,110,Anjali,23,0,Mumbai,2025-03-15,5,82,80,30000,40000,10000,Excellent,2025,False,True,False

In [25]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
student_df['age'] = std_scaler.fit_transform(student_df[['age']])
student_df

,student_id,name,age,gender,city,joining_date,study_hours,attendance,marks,fees_paid,fees_total,remaining_fees,performance,year,course_Data Analytics,course_Data Science,course_Python
0,101,Rahul,-0.714435,1,Pune,2025-01-15,5,85,78,35000,40000,5000,Good,2025,False,True,False
1,102,Priya,-1.224745,0,Mumbai,2025-02-10,3,72,65,30000,40000,10000,Good,2025,True,False,False
2,103,Amit,0.306186,1,Pune,2025-01-20,7,91,88,40000,40000,0,Excellent,2025,False,True,False
3,104,Sneha,-0.204124,0,Nashik,2025-03-05,2,60,55,20000,30000,10000,Poor,2025,False,False,True
4,105,Karan,0.816497,1,Mumbai,2025-01-25,6,95,92,35000,40000,5000,Excellent,2025,True,False,False
5,106,Neha,-0.714435,0,Pune,2025-02-18,4,78,70,25000,30000,5000,Good,2025,False,False,True
6,107,Rohit,1.837117,1,Nagpur,2025-03-12,1,55,45,15000,40000,25000,Poor,2025,False,True,False
7,108,Pooja,-1.224745,0,Nashik,2025-02-22,8,97,95,40000,40000,0,Excellent,2025,True,False,False
8,109,Vikram,1.326807,1,Pune,2025-01-30,3,68,60,22000,30000,8000,Good,2025,False,False,True
9,110,Anjali,-0.204124,0,Mumbai,2025-03-15,5,82,80,30000,40000,10000,Excellent,2025,False,True,False

In [27]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
student_df[['study_hours',"attendance",'marks']] = std_scaler.fit_transform(student_df[['study_hours',"attendance",'marks']])

In [30]:
student_df.isnull().sum()

student_id               0
name                     0
age                      0
gender                   0
city                     0
joining_date             0
study_hours              0
attendance               0
marks                    0
fees_paid                0
fees_total               0
remaining_fees           0
performance              0
year                     0
course_Data Analytics    0
course_Data Science      0
course_Python            0
dtype: int64

In [37]:
student_df = student_df.drop(columns=['student_id','name'])

In [38]:
student_df

,age,gender,city,joining_date,study_hours,attendance,marks,fees_paid,fees_total,remaining_fees,performance,year,course_Data Analytics,course_Data Science,course_Python
0,-0.714435,1,Pune,2025-01-15,0.284747,0.489678,0.329299,35000,40000,5000,Good,2025,False,True,False
1,-1.224745,0,Mumbai,2025-02-10,-0.664411,-0.460443,-0.493948,30000,40000,10000,Good,2025,True,False,False
2,0.306186,1,Pune,2025-01-20,1.233905,0.928195,0.962565,40000,40000,0,Excellent,2025,False,True,False
3,-0.204124,0,Nashik,2025-03-05,-1.138990,-1.337478,-1.127215,20000,30000,10000,Poor,2025,False,False,True
4,0.816497,1,Mumbai,2025-01-25,0.759326,1.220540,1.215872,35000,40000,5000,Excellent,2025,True,False,False
5,-0.714435,0,Pune,2025-02-18,-0.189832,-0.021926,-0.177315,25000,30000,5000,Good,2025,False,False,True
6,1.837117,1,Nagpur,2025-03-12,-1.613569,-1.702909,-1.760481,15000,40000,25000,Poor,2025,False,True,False
7,-1.224745,0,Nashik,2025-02-22,1.708484,1.366712,1.405852,40000,40000,0,Excellent,2025,True,False,False
8,1.326807,1,Pune,2025-01-30,-0.664411,-0.752788,-0.810581,22000,30000,8000,Good,2025,False,False,True
9,-0.204124,0,Mumbai,2025-03-15,0.284747,0.270419,0.455952,30000,40000,10000,Excellent,2025,False,True,False