In [1]:
import pandas as pd

In [2]:
student_df = pd.read_excel("student_data.xlsx")
student_df

,student_id,name,age,gender,city,course,joining_date,study_hours,attendance,marks,fees_paid,fees_total
0,101,Rahul,22,Male,Pune,Data Science,2025-01-15,5,85,78,35000,40000
1,102,Priya,21,Female,Mumbai,Data Analytics,2025-02-10,3,72,65,30000,40000
2,103,Amit,24,Male,Pune,Data Science,2025-01-20,7,91,88,40000,40000
3,104,Sneha,23,Female,Nashik,Python,2025-03-05,2,60,55,20000,30000
4,105,Karan,25,Male,Mumbai,Data Analytics,2025-01-25,6,95,92,35000,40000
5,106,Neha,22,Female,Pune,Python,2025-02-18,4,78,70,25000,30000
6,107,Rohit,27,Male,Nagpur,Data Science,2025-03-12,1,55,45,15000,40000
7,108,Pooja,21,Female,Nashik,Data Analytics,2025-02-22,8,97,95,40000,40000
8,109,Vikram,26,Male,Pune,Python,2025-01-30,3,68,60,22000,30000
9,110,Anjali,23,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000
10,111,ajay,67,Male,Pune,Python,2025-01-30,3,68,60,22000,30000
11,112,suraj,45,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000
12,113,vijay,72,Male,Pune,Python,2025-01-30,3,68,60,22000,30000
13,114,kunal,56,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000

In [3]:
student_df["remaining_fees"] = student_df["fees_total"]- student_df["fees_paid"]

In [4]:
student_df

,student_id,name,age,gender,city,course,joining_date,study_hours,attendance,marks,fees_paid,fees_total,remaining_fees
0,101,Rahul,22,Male,Pune,Data Science,2025-01-15,5,85,78,35000,40000,5000
1,102,Priya,21,Female,Mumbai,Data Analytics,2025-02-10,3,72,65,30000,40000,10000
2,103,Amit,24,Male,Pune,Data Science,2025-01-20,7,91,88,40000,40000,0
3,104,Sneha,23,Female,Nashik,Python,2025-03-05,2,60,55,20000,30000,10000
4,105,Karan,25,Male,Mumbai,Data Analytics,2025-01-25,6,95,92,35000,40000,5000
5,106,Neha,22,Female,Pune,Python,2025-02-18,4,78,70,25000,30000,5000
6,107,Rohit,27,Male,Nagpur,Data Science,2025-03-12,1,55,45,15000,40000,25000
7,108,Pooja,21,Female,Nashik,Data Analytics,2025-02-22,8,97,95,40000,40000,0
8,109,Vikram,26,Male,Pune,Python,2025-01-30,3,68,60,22000,30000,8000
9,110,Anjali,23,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,10000
10,111,ajay,67,Male,Pune,Python,2025-01-30,3,68,60,22000,30000,8000
11,112,suraj,45,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,10000
12,113,vijay,72,Male,Pune,Python,2025-01-30,3,68,60,22000,30000,8000
13,114,kunal,56,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,10000

In [5]:
def student_performance(marks):
    if marks>80:
        return "Excellent"
    elif marks>60:
        return "Good"
    else:
        return "Poor"
per = student_df["marks"].apply(student_performance)
student_df["performance"]=per
student_df

,student_id,name,age,gender,city,course,joining_date,study_hours,attendance,marks,fees_paid,fees_total,remaining_fees,performance
0,101,Rahul,22,Male,Pune,Data Science,2025-01-15,5,85,78,35000,40000,5000,Good
1,102,Priya,21,Female,Mumbai,Data Analytics,2025-02-10,3,72,65,30000,40000,10000,Good
2,103,Amit,24,Male,Pune,Data Science,2025-01-20,7,91,88,40000,40000,0,Excellent
3,104,Sneha,23,Female,Nashik,Python,2025-03-05,2,60,55,20000,30000,10000,Poor
4,105,Karan,25,Male,Mumbai,Data Analytics,2025-01-25,6,95,92,35000,40000,5000,Excellent
5,106,Neha,22,Female,Pune,Python,2025-02-18,4,78,70,25000,30000,5000,Good
6,107,Rohit,27,Male,Nagpur,Data Science,2025-03-12,1,55,45,15000,40000,25000,Poor
7,108,Pooja,21,Female,Nashik,Data Analytics,2025-02-22,8,97,95,40000,40000,0,Excellent
8,109,Vikram,26,Male,Pune,Python,2025-01-30,3,68,60,22000,30000,8000,Poor
9,110,Anjali,23,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,10000,Good
10,111,ajay,67,Male,Pune,Python,2025-01-30,3,68,60,22000,30000,8000,Poor
11,112,suraj,45,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,10000,Good
12,113,vijay,72,Male,Pune,Python,2025-01-30,3,68,60,22000,30000,8000,Poor
13,114,kunal,56,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,10000,Good

In [7]:
student_df["year"] = student_df["joining_date"].dt.year
student_df

,student_id,name,age,gender,city,course,joining_date,study_hours,attendance,marks,fees_paid,fees_total,remaining_fees,performance,year
0,101,Rahul,22,Male,Pune,Data Science,2025-01-15,5,85,78,35000,40000,5000,Good,2025
1,102,Priya,21,Female,Mumbai,Data Analytics,2025-02-10,3,72,65,30000,40000,10000,Good,2025
2,103,Amit,24,Male,Pune,Data Science,2025-01-20,7,91,88,40000,40000,0,Excellent,2025
3,104,Sneha,23,Female,Nashik,Python,2025-03-05,2,60,55,20000,30000,10000,Poor,2025
4,105,Karan,25,Male,Mumbai,Data Analytics,2025-01-25,6,95,92,35000,40000,5000,Excellent,2025
5,106,Neha,22,Female,Pune,Python,2025-02-18,4,78,70,25000,30000,5000,Good,2025
6,107,Rohit,27,Male,Nagpur,Data Science,2025-03-12,1,55,45,15000,40000,25000,Poor,2025
7,108,Pooja,21,Female,Nashik,Data Analytics,2025-02-22,8,97,95,40000,40000,0,Excellent,2025
8,109,Vikram,26,Male,Pune,Python,2025-01-30,3,68,60,22000,30000,8000,Poor,2025
9,110,Anjali,23,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,10000,Good,2025
10,111,ajay,67,Male,Pune,Python,2025-01-30,3,68,60,22000,30000,8000,Poor,2025
11,112,suraj,45,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,10000,Good,2025
12,113,vijay,72,Male,Pune,Python,2025-01-30,3,68,60,22000,30000,8000,Poor,2025
13,114,kunal,56,Female,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,10000,Good,2025

In [9]:
from sklearn.preprocessing import LabelEncoder
label_en = LabelEncoder()
student_df["gender"]=label_en.fit_transform(student_df["gender"])
student_df

,student_id,name,age,gender,city,course,joining_date,study_hours,attendance,marks,fees_paid,fees_total,remaining_fees,performance,year
0,101,Rahul,22,1,Pune,Data Science,2025-01-15,5,85,78,35000,40000,5000,Good,2025
1,102,Priya,21,0,Mumbai,Data Analytics,2025-02-10,3,72,65,30000,40000,10000,Good,2025
2,103,Amit,24,1,Pune,Data Science,2025-01-20,7,91,88,40000,40000,0,Excellent,2025
3,104,Sneha,23,0,Nashik,Python,2025-03-05,2,60,55,20000,30000,10000,Poor,2025
4,105,Karan,25,1,Mumbai,Data Analytics,2025-01-25,6,95,92,35000,40000,5000,Excellent,2025
5,106,Neha,22,0,Pune,Python,2025-02-18,4,78,70,25000,30000,5000,Good,2025
6,107,Rohit,27,1,Nagpur,Data Science,2025-03-12,1,55,45,15000,40000,25000,Poor,2025
7,108,Pooja,21,0,Nashik,Data Analytics,2025-02-22,8,97,95,40000,40000,0,Excellent,2025
8,109,Vikram,26,1,Pune,Python,2025-01-30,3,68,60,22000,30000,8000,Poor,2025
9,110,Anjali,23,0,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,10000,Good,2025
10,111,ajay,67,1,Pune,Python,2025-01-30,3,68,60,22000,30000,8000,Poor,2025
11,112,suraj,45,0,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,10000,Good,2025
12,113,vijay,72,1,Pune,Python,2025-01-30,3,68,60,22000,30000,8000,Poor,2025
13,114,kunal,56,0,Mumbai,Data Science,2025-03-15,5,82,80,30000,40000,10000,Good,2025

In [11]:
student_df["gender"]=label_en.fit_transform(student_df["gender"])
student_df = pd.get_dummies(student_df,columns=["course"])
student_df

,student_id,name,age,gender,city,joining_date,study_hours,attendance,marks,fees_paid,fees_total,remaining_fees,performance,year,course_Data Analytics,course_Data Science,course_Python
0,101,Rahul,22,1,Pune,2025-01-15,5,85,78,35000,40000,5000,Good,2025,False,True,False
1,102,Priya,21,0,Mumbai,2025-02-10,3,72,65,30000,40000,10000,Good,2025,True,False,False
2,103,Amit,24,1,Pune,2025-01-20,7,91,88,40000,40000,0,Excellent,2025,False,True,False
3,104,Sneha,23,0,Nashik,2025-03-05,2,60,55,20000,30000,10000,Poor,2025,False,False,True
4,105,Karan,25,1,Mumbai,2025-01-25,6,95,92,35000,40000,5000,Excellent,2025,True,False,False
5,106,Neha,22,0,Pune,2025-02-18,4,78,70,25000,30000,5000,Good,2025,False,False,True
6,107,Rohit,27,1,Nagpur,2025-03-12,1,55,45,15000,40000,25000,Poor,2025,False,True,False
7,108,Pooja,21,0,Nashik,2025-02-22,8,97,95,40000,40000,0,Excellent,2025,True,False,False
8,109,Vikram,26,1,Pune,2025-01-30,3,68,60,22000,30000,8000,Poor,2025,False,False,True
9,110,Anjali,23,0,Mumbai,2025-03-15,5,82,80,30000,40000,10000,Good,2025,False,True,False
10,111,ajay,67,1,Pune,2025-01-30,3,68,60,22000,30000,8000,Poor,2025,False,False,True
11,112,suraj,45,0,Mumbai,2025-03-15,5,82,80,30000,40000,10000,Good,2025,False,True,False
12,113,vijay,72,1,Pune,2025-01-30,3,68,60,22000,30000,8000,Poor,2025,False,False,True
13,114,kunal,56,0,Mumbai,2025-03-15,5,82,80,30000,40000,10000,Good,2025,False,True,False

In [13]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
student_df['age'] = std_scaler.fit_transform(student_df[["age"]])
student_df

,student_id,name,age,gender,city,joining_date,study_hours,attendance,marks,fees_paid,fees_total,remaining_fees,performance,year,course_Data Analytics,course_Data Science,course_Python
0,101,Rahul,-0.676588,1,Pune,2025-01-15,5,85,78,35000,40000,5000,Good,2025,False,True,False
1,102,Priya,-0.733650,0,Mumbai,2025-02-10,3,72,65,30000,40000,10000,Good,2025,True,False,False
2,103,Amit,-0.562465,1,Pune,2025-01-20,7,91,88,40000,40000,0,Excellent,2025,False,True,False
3,104,Sneha,-0.619526,0,Nashik,2025-03-05,2,60,55,20000,30000,10000,Poor,2025,False,False,True
4,105,Karan,-0.505403,1,Mumbai,2025-01-25,6,95,92,35000,40000,5000,Excellent,2025,True,False,False
5,106,Neha,-0.676588,0,Pune,2025-02-18,4,78,70,25000,30000,5000,Good,2025,False,False,True
6,107,Rohit,-0.391280,1,Nagpur,2025-03-12,1,55,45,15000,40000,25000,Poor,2025,False,True,False
7,108,Pooja,-0.733650,0,Nashik,2025-02-22,8,97,95,40000,40000,0,Excellent,2025,True,False,False
8,109,Vikram,-0.448341,1,Pune,2025-01-30,3,68,60,22000,30000,8000,Poor,2025,False,False,True
9,110,Anjali,-0.619526,0,Mumbai,2025-03-15,5,82,80,30000,40000,10000,Good,2025,False,True,False
10,111,ajay,1.891186,1,Pune,2025-01-30,3,68,60,22000,30000,8000,Poor,2025,False,False,True
11,112,suraj,0.635830,0,Mumbai,2025-03-15,5,82,80,30000,40000,10000,Good,2025,False,True,False
12,113,vijay,2.176494,1,Pune,2025-01-30,3,68,60,22000,30000,8000,Poor,2025,False,False,True
13,114,kunal,1.263508,0,Mumbai,2025-03-15,5,82,80,30000,40000,10000,Good,2025,False,True,False

In [15]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
student_df[['study_hours','attendance','marks']] = std_scaler.fit_transform(student_df[['study_hours','attendance','marks']])

In [16]:
student_df

,student_id,name,age,gender,city,joining_date,study_hours,attendance,marks,fees_paid,fees_total,remaining_fees,performance,year,course_Data Analytics,course_Data Science,course_Python
0,101,Rahul,-0.676588,1,Pune,2025-01-15,0.382360,0.624153,0.415740,35000,40000,5000,Good,2025,False,True,False
1,102,Priya,-0.733650,0,Mumbai,2025-02-10,-0.688247,-0.437491,-0.485030,30000,40000,10000,Good,2025,True,False,False
2,103,Amit,-0.562465,1,Pune,2025-01-20,1.452966,1.114143,1.108639,40000,40000,0,Excellent,2025,False,True,False
3,104,Sneha,-0.619526,0,Nashik,2025-03-05,-1.223551,-1.417470,-1.177929,20000,30000,10000,Poor,2025,False,False,True
4,105,Karan,-0.505403,1,Mumbai,2025-01-25,0.917663,1.440803,1.385799,35000,40000,5000,Excellent,2025,True,False,False
5,106,Neha,-0.676588,0,Pune,2025-02-18,-0.152944,0.052499,-0.138580,25000,30000,5000,Good,2025,False,False,True
6,107,Rohit,-0.391280,1,Nagpur,2025-03-12,-1.758854,-1.825795,-1.870829,15000,40000,25000,Poor,2025,False,True,False
7,108,Pooja,-0.733650,0,Nashik,2025-02-22,1.988270,1.604133,1.593669,40000,40000,0,Excellent,2025,True,False,False
8,109,Vikram,-0.448341,1,Pune,2025-01-30,-0.688247,-0.764150,-0.831479,22000,30000,8000,Poor,2025,False,False,True
9,110,Anjali,-0.619526,0,Mumbai,2025-03-15,0.382360,0.379159,0.554320,30000,40000,10000,Good,2025,False,True,False
10,111,ajay,1.891186,1,Pune,2025-01-30,-0.688247,-0.764150,-0.831479,22000,30000,8000,Poor,2025,False,False,True
11,112,suraj,0.635830,0,Mumbai,2025-03-15,0.382360,0.379159,0.554320,30000,40000,10000,Good,2025,False,True,False
12,113,vijay,2.176494,1,Pune,2025-01-30,-0.688247,-0.764150,-0.831479,22000,30000,8000,Poor,2025,False,False,True
13,114,kunal,1.263508,0,Mumbai,2025-03-15,0.382360,0.379159,0.554320,30000,40000,10000,Good,2025,False,True,False

In [17]:
student_df.isnull().sum()

student_id               0
name                     0
age                      0
gender                   0
city                     0
joining_date             0
study_hours              0
attendance               0
marks                    0
fees_paid                0
fees_total               0
remaining_fees           0
performance              0
year                     0
course_Data Analytics    0
course_Data Science      0
course_Python            0
dtype: int64

In [20]:
student_df.drop(labels=['student_id'],axis=1)

,name,age,gender,city,joining_date,study_hours,attendance,marks,fees_paid,fees_total,remaining_fees,performance,year,course_Data Analytics,course_Data Science,course_Python
0,Rahul,-0.676588,1,Pune,2025-01-15,0.382360,0.624153,0.415740,35000,40000,5000,Good,2025,False,True,False
1,Priya,-0.733650,0,Mumbai,2025-02-10,-0.688247,-0.437491,-0.485030,30000,40000,10000,Good,2025,True,False,False
2,Amit,-0.562465,1,Pune,2025-01-20,1.452966,1.114143,1.108639,40000,40000,0,Excellent,2025,False,True,False
3,Sneha,-0.619526,0,Nashik,2025-03-05,-1.223551,-1.417470,-1.177929,20000,30000,10000,Poor,2025,False,False,True
4,Karan,-0.505403,1,Mumbai,2025-01-25,0.917663,1.440803,1.385799,35000,40000,5000,Excellent,2025,True,False,False
5,Neha,-0.676588,0,Pune,2025-02-18,-0.152944,0.052499,-0.138580,25000,30000,5000,Good,2025,False,False,True
6,Rohit,-0.391280,1,Nagpur,2025-03-12,-1.758854,-1.825795,-1.870829,15000,40000,25000,Poor,2025,False,True,False
7,Pooja,-0.733650,0,Nashik,2025-02-22,1.988270,1.604133,1.593669,40000,40000,0,Excellent,2025,True,False,False
8,Vikram,-0.448341,1,Pune,2025-01-30,-0.688247,-0.764150,-0.831479,22000,30000,8000,Poor,2025,False,False,True
9,Anjali,-0.619526,0,Mumbai,2025-03-15,0.382360,0.379159,0.554320,30000,40000,10000,Good,2025,False,True,False
10,ajay,1.891186,1,Pune,2025-01-30,-0.688247,-0.764150,-0.831479,22000,30000,8000,Poor,2025,False,False,True
11,suraj,0.635830,0,Mumbai,2025-03-15,0.382360,0.379159,0.554320,30000,40000,10000,Good,2025,False,True,False
12,vijay,2.176494,1,Pune,2025-01-30,-0.688247,-0.764150,-0.831479,22000,30000,8000,Poor,2025,False,False,True
13,kunal,1.263508,0,Mumbai,2025-03-15,0.382360,0.379159,0.554320,30000,40000,10000,Good,2025,False,True,False

In [21]:
student_df=student_df.drop(columns=['student_id','name'])

In [22]:
student_df

,age,gender,city,joining_date,study_hours,attendance,marks,fees_paid,fees_total,remaining_fees,performance,year,course_Data Analytics,course_Data Science,course_Python
0,-0.676588,1,Pune,2025-01-15,0.382360,0.624153,0.415740,35000,40000,5000,Good,2025,False,True,False
1,-0.733650,0,Mumbai,2025-02-10,-0.688247,-0.437491,-0.485030,30000,40000,10000,Good,2025,True,False,False
2,-0.562465,1,Pune,2025-01-20,1.452966,1.114143,1.108639,40000,40000,0,Excellent,2025,False,True,False
3,-0.619526,0,Nashik,2025-03-05,-1.223551,-1.417470,-1.177929,20000,30000,10000,Poor,2025,False,False,True
4,-0.505403,1,Mumbai,2025-01-25,0.917663,1.440803,1.385799,35000,40000,5000,Excellent,2025,True,False,False
5,-0.676588,0,Pune,2025-02-18,-0.152944,0.052499,-0.138580,25000,30000,5000,Good,2025,False,False,True
6,-0.391280,1,Nagpur,2025-03-12,-1.758854,-1.825795,-1.870829,15000,40000,25000,Poor,2025,False,True,False
7,-0.733650,0,Nashik,2025-02-22,1.988270,1.604133,1.593669,40000,40000,0,Excellent,2025,True,False,False
8,-0.448341,1,Pune,2025-01-30,-0.688247,-0.764150,-0.831479,22000,30000,8000,Poor,2025,False,False,True
9,-0.619526,0,Mumbai,2025-03-15,0.382360,0.379159,0.554320,30000,40000,10000,Good,2025,False,True,False
10,1.891186,1,Pune,2025-01-30,-0.688247,-0.764150,-0.831479,22000,30000,8000,Poor,2025,False,False,True
11,0.635830,0,Mumbai,2025-03-15,0.382360,0.379159,0.554320,30000,40000,10000,Good,2025,False,True,False
12,2.176494,1,Pune,2025-01-30,-0.688247,-0.764150,-0.831479,22000,30000,8000,Poor,2025,False,False,True
13,1.263508,0,Mumbai,2025-03-15,0.382360,0.379159,0.554320,30000,40000,10000,Good,2025,False,True,False