In [1]:
import pandas as pd

In [2]:
student_admission_df = pd.read_excel("student_admission.xlsx")
student_admission_df

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor
0,S101,Amit,Chinchwad,Data Analytics,2026-01-10,Rahul
1,S102,Sneha,Hadapsar,Data Science,2026-01-12,Priya
2,S103,Rohit,Karve Nagar,Python Full Stack,2026-01-15,Amit
3,S104,Pooja,Chinchwad,Data Analytics,2026-01-18,Rahul
4,S105,Akash,Nagpur,Java Full Stack,2026-01-20,Neha
5,S106,Neha,Hadapsar,Testing,2026-01-22,Priya
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit
7,S108,Snehal,Karve Nagar,Python Full Stack,2026-02-02,Neha
8,S109,Kunal,Nagpur,Data Analytics,2026-02-05,Rahul
9,S110,Priyanka,Hadapsar,Data Science,2026-02-08,Priya

In [3]:
student_payment_df = pd.read_excel("student_payment.xlsx")
student_payment_df

  Student_ID  Total_Fees  Paid_Fees Payment_Mode
0       S101       40000      30000          UPI
1       S102       50000      50000         Cash
2       S103       30000      20000          UPI
3       S104       40000      40000         Card
4       S105       30000      15000          UPI
5       S106       25000      25000         Cash
6       S107       50000      30000         Card
7       S108       30000      30000          UPI
8       S109       40000      25000         Cash
9       S110       50000      35000          UPI

In [4]:
student_payment_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    10 non-null     str
 1   Total_Fees    10 non-null     int64
 2   Paid_Fees     10 non-null     int64
 3   Payment_Mode  10 non-null     str
dtypes: int64(2), str(2)
memory usage: 452.0 bytes

In [5]:
# no of rowa
# len(student_payment_df)
len(student_admission_df)

10

In [6]:
# no of columns
# len(student_admission_df.columns)
len(student_payment_df.columns)

4

In [7]:
#Column names
# student_admission_df.columns
student_payment_df.columns

Index(['Student_ID', 'Total_Fees', 'Paid_Fees', 'Payment_Mode'], dtype='str')

In [8]:
#datatypes
student_payment_df.dtypes
student_admission_df.dtypes

Student_ID        str
Student_Name      str
Branch            str
Course            str
Admission_Date    str
Counselor         str
dtype: object

In [9]:
#merge
admission_df = pd.merge(student_admission_df,student_payment_df,how = "inner",on = "Student_ID")
admission_df

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode
0,S101,Amit,Chinchwad,Data Analytics,2026-01-10,Rahul,40000,30000,UPI
1,S102,Sneha,Hadapsar,Data Science,2026-01-12,Priya,50000,50000,Cash
2,S103,Rohit,Karve Nagar,Python Full Stack,2026-01-15,Amit,30000,20000,UPI
3,S104,Pooja,Chinchwad,Data Analytics,2026-01-18,Rahul,40000,40000,Card
4,S105,Akash,Nagpur,Java Full Stack,2026-01-20,Neha,30000,15000,UPI
5,S106,Neha,Hadapsar,Testing,2026-01-22,Priya,25000,25000,Cash
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit,50000,30000,Card
7,S108,Snehal,Karve Nagar,Python Full Stack,2026-02-02,Neha,30000,30000,UPI
8,S109,Kunal,Nagpur,Data Analytics,2026-02-05,Rahul,40000,25000,Cash
9,S110,Priyanka,Hadapsar,Data Science,2026-02-08,Priya,50000,35000,UPI

In [10]:
admission_df.head(1)

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode
0,S101,Amit,Chinchwad,Data Analytics,2026-01-10,Rahul,40000,30000,UPI

In [11]:
admission_df.iloc[0]

Student_ID                  S101
Student_Name                Amit
Branch                 Chinchwad
Course            Data Analytics
Admission_Date        2026-01-10
Counselor                  Rahul
Total_Fees                 40000
Paid_Fees                  30000
Payment_Mode                 UPI
Name: 0, dtype: object

In [12]:
admission_df.iloc[-1]

Student_ID                S110
Student_Name          Priyanka
Branch                Hadapsar
Course            Data Science
Admission_Date      2026-02-08
Counselor                Priya
Total_Fees               50000
Paid_Fees                35000
Payment_Mode               UPI
Name: 9, dtype: object

In [13]:
admission_df.head()

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode
0,S101,Amit,Chinchwad,Data Analytics,2026-01-10,Rahul,40000,30000,UPI
1,S102,Sneha,Hadapsar,Data Science,2026-01-12,Priya,50000,50000,Cash
2,S103,Rohit,Karve Nagar,Python Full Stack,2026-01-15,Amit,30000,20000,UPI
3,S104,Pooja,Chinchwad,Data Analytics,2026-01-18,Rahul,40000,40000,Card
4,S105,Akash,Nagpur,Java Full Stack,2026-01-20,Neha,30000,15000,UPI

In [14]:
admission_df.iloc[2:7]

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode
2,S103,Rohit,Karve Nagar,Python Full Stack,2026-01-15,Amit,30000,20000,UPI
3,S104,Pooja,Chinchwad,Data Analytics,2026-01-18,Rahul,40000,40000,Card
4,S105,Akash,Nagpur,Java Full Stack,2026-01-20,Neha,30000,15000,UPI
5,S106,Neha,Hadapsar,Testing,2026-01-22,Priya,25000,25000,Cash
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit,50000,30000,Card

In [15]:
admission_df[admission_df["Student_ID"]=='S105']

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode
4,S105,Akash,Nagpur,Java Full Stack,2026-01-20,Neha,30000,15000,UPI

In [16]:
admission_df[admission_df["Branch"]=="Chinchwad"]

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode
0,S101,Amit,Chinchwad,Data Analytics,2026-01-10,Rahul,40000,30000,UPI
3,S104,Pooja,Chinchwad,Data Analytics,2026-01-18,Rahul,40000,40000,Card
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit,50000,30000,Card

In [17]:
admission_df["Student_Name"]

0        Amit
1       Sneha
2       Rohit
3       Pooja
4       Akash
5        Neha
6       Rahul
7      Snehal
8       Kunal
9    Priyanka
Name: Student_Name, dtype: str

In [18]:
admission_df["Course"]

0       Data Analytics
1         Data Science
2    Python Full Stack
3       Data Analytics
4      Java Full Stack
5              Testing
6         Data Science
7    Python Full Stack
8       Data Analytics
9         Data Science
Name: Course, dtype: str

In [19]:
admission_df[["Student_Name","Branch","Course","Paid_Fees"]]

  Student_Name       Branch             Course  Paid_Fees
0         Amit    Chinchwad     Data Analytics      30000
1        Sneha     Hadapsar       Data Science      50000
2        Rohit  Karve Nagar  Python Full Stack      20000
3        Pooja    Chinchwad     Data Analytics      40000
4        Akash       Nagpur    Java Full Stack      15000
5         Neha     Hadapsar            Testing      25000
6        Rahul    Chinchwad       Data Science      30000
7       Snehal  Karve Nagar  Python Full Stack      30000
8        Kunal       Nagpur     Data Analytics      25000
9     Priyanka     Hadapsar       Data Science      35000

In [20]:
admission_df.drop(columns = ["Payment_Mode"])

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees
0,S101,Amit,Chinchwad,Data Analytics,2026-01-10,Rahul,40000,30000
1,S102,Sneha,Hadapsar,Data Science,2026-01-12,Priya,50000,50000
2,S103,Rohit,Karve Nagar,Python Full Stack,2026-01-15,Amit,30000,20000
3,S104,Pooja,Chinchwad,Data Analytics,2026-01-18,Rahul,40000,40000
4,S105,Akash,Nagpur,Java Full Stack,2026-01-20,Neha,30000,15000
5,S106,Neha,Hadapsar,Testing,2026-01-22,Priya,25000,25000
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit,50000,30000
7,S108,Snehal,Karve Nagar,Python Full Stack,2026-02-02,Neha,30000,30000
8,S109,Kunal,Nagpur,Data Analytics,2026-02-05,Rahul,40000,25000
9,S110,Priyanka,Hadapsar,Data Science,2026-02-08,Priya,50000,35000

In [21]:
admission_df["Remaining_Fees"] = admission_df["Total_Fees"]-admission_df["Paid_Fees"]

In [22]:
admission_df

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode,Remaining_Fees
0,S101,Amit,Chinchwad,Data Analytics,2026-01-10,Rahul,40000,30000,UPI,10000
1,S102,Sneha,Hadapsar,Data Science,2026-01-12,Priya,50000,50000,Cash,0
2,S103,Rohit,Karve Nagar,Python Full Stack,2026-01-15,Amit,30000,20000,UPI,10000
3,S104,Pooja,Chinchwad,Data Analytics,2026-01-18,Rahul,40000,40000,Card,0
4,S105,Akash,Nagpur,Java Full Stack,2026-01-20,Neha,30000,15000,UPI,15000
5,S106,Neha,Hadapsar,Testing,2026-01-22,Priya,25000,25000,Cash,0
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit,50000,30000,Card,20000
7,S108,Snehal,Karve Nagar,Python Full Stack,2026-02-02,Neha,30000,30000,UPI,0
8,S109,Kunal,Nagpur,Data Analytics,2026-02-05,Rahul,40000,25000,Cash,15000
9,S110,Priyanka,Hadapsar,Data Science,2026-02-08,Priya,50000,35000,UPI,15000

In [23]:
admission_df["Payment_Status"] = admission_df["Remaining_Fees"].apply(lambda x: "Fully Paid" if x==0 else "Pending")

In [24]:
admission_df

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode,Remaining_Fees,Payment_Status
0,S101,Amit,Chinchwad,Data Analytics,2026-01-10,Rahul,40000,30000,UPI,10000,Pending
1,S102,Sneha,Hadapsar,Data Science,2026-01-12,Priya,50000,50000,Cash,0,Fully Paid
2,S103,Rohit,Karve Nagar,Python Full Stack,2026-01-15,Amit,30000,20000,UPI,10000,Pending
3,S104,Pooja,Chinchwad,Data Analytics,2026-01-18,Rahul,40000,40000,Card,0,Fully Paid
4,S105,Akash,Nagpur,Java Full Stack,2026-01-20,Neha,30000,15000,UPI,15000,Pending
5,S106,Neha,Hadapsar,Testing,2026-01-22,Priya,25000,25000,Cash,0,Fully Paid
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit,50000,30000,Card,20000,Pending
7,S108,Snehal,Karve Nagar,Python Full Stack,2026-02-02,Neha,30000,30000,UPI,0,Fully Paid
8,S109,Kunal,Nagpur,Data Analytics,2026-02-05,Rahul,40000,25000,Cash,15000,Pending
9,S110,Priyanka,Hadapsar,Data Science,2026-02-08,Priya,50000,35000,UPI,15000,Pending

In [25]:
admission_df.loc[len(admission_df)] = ["S111","Vaibhav","Chinchwad","Data Analytics","2026-02-10","Rahul",40000,20000,"UPI",20000,"Pending"]

In [26]:
admission_df

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode,Remaining_Fees,Payment_Status
0,S101,Amit,Chinchwad,Data Analytics,2026-01-10,Rahul,40000,30000,UPI,10000,Pending
1,S102,Sneha,Hadapsar,Data Science,2026-01-12,Priya,50000,50000,Cash,0,Fully Paid
2,S103,Rohit,Karve Nagar,Python Full Stack,2026-01-15,Amit,30000,20000,UPI,10000,Pending
3,S104,Pooja,Chinchwad,Data Analytics,2026-01-18,Rahul,40000,40000,Card,0,Fully Paid
4,S105,Akash,Nagpur,Java Full Stack,2026-01-20,Neha,30000,15000,UPI,15000,Pending
5,S106,Neha,Hadapsar,Testing,2026-01-22,Priya,25000,25000,Cash,0,Fully Paid
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit,50000,30000,Card,20000,Pending
7,S108,Snehal,Karve Nagar,Python Full Stack,2026-02-02,Neha,30000,30000,UPI,0,Fully Paid
8,S109,Kunal,Nagpur,Data Analytics,2026-02-05,Rahul,40000,25000,Cash,15000,Pending
9,S110,Priyanka,Hadapsar,Data Science,2026-02-08,Priya,50000,35000,UPI,15000,Pending
10,S111,Vaibhav,Chinchwad,Data Analytics,2026-02-10,Rahul,40000,20000,UPI,20000,Pending

In [27]:
admission_df[admission_df['Student_ID']!='S105']

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode,Remaining_Fees,Payment_Status
0,S101,Amit,Chinchwad,Data Analytics,2026-01-10,Rahul,40000,30000,UPI,10000,Pending
1,S102,Sneha,Hadapsar,Data Science,2026-01-12,Priya,50000,50000,Cash,0,Fully Paid
2,S103,Rohit,Karve Nagar,Python Full Stack,2026-01-15,Amit,30000,20000,UPI,10000,Pending
3,S104,Pooja,Chinchwad,Data Analytics,2026-01-18,Rahul,40000,40000,Card,0,Fully Paid
5,S106,Neha,Hadapsar,Testing,2026-01-22,Priya,25000,25000,Cash,0,Fully Paid
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit,50000,30000,Card,20000,Pending
7,S108,Snehal,Karve Nagar,Python Full Stack,2026-02-02,Neha,30000,30000,UPI,0,Fully Paid
8,S109,Kunal,Nagpur,Data Analytics,2026-02-05,Rahul,40000,25000,Cash,15000,Pending
9,S110,Priyanka,Hadapsar,Data Science,2026-02-08,Priya,50000,35000,UPI,15000,Pending
10,S111,Vaibhav,Chinchwad,Data Analytics,2026-02-10,Rahul,40000,20000,UPI,20000,Pending

In [28]:
admission_df.drop(columns = ["Payment_Mode"])

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Remaining_Fees,Payment_Status
0,S101,Amit,Chinchwad,Data Analytics,2026-01-10,Rahul,40000,30000,10000,Pending
1,S102,Sneha,Hadapsar,Data Science,2026-01-12,Priya,50000,50000,0,Fully Paid
2,S103,Rohit,Karve Nagar,Python Full Stack,2026-01-15,Amit,30000,20000,10000,Pending
3,S104,Pooja,Chinchwad,Data Analytics,2026-01-18,Rahul,40000,40000,0,Fully Paid
4,S105,Akash,Nagpur,Java Full Stack,2026-01-20,Neha,30000,15000,15000,Pending
5,S106,Neha,Hadapsar,Testing,2026-01-22,Priya,25000,25000,0,Fully Paid
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit,50000,30000,20000,Pending
7,S108,Snehal,Karve Nagar,Python Full Stack,2026-02-02,Neha,30000,30000,0,Fully Paid
8,S109,Kunal,Nagpur,Data Analytics,2026-02-05,Rahul,40000,25000,15000,Pending
9,S110,Priyanka,Hadapsar,Data Science,2026-02-08,Priya,50000,35000,15000,Pending
10,S111,Vaibhav,Chinchwad,Data Analytics,2026-02-10,Rahul,40000,20000,20000,Pending

In [29]:
Total_Students = admission_df["Student_ID"].count()
Total_Students

np.int64(11)

In [30]:
len(admission_df)

11

In [31]:
Total_Fees=admission_df["Total_Fees"].sum()
Total_Fees

np.int64(425000)

In [32]:
Total_Paid_Fees = admission_df["Paid_Fees"].sum()
Total_Paid_Fees

np.int64(320000)

In [33]:
Total_Remaining_Fees = admission_df["Remaining_Fees"].sum()
Total_Remaining_Fees

np.int64(105000)

In [34]:
Average_Fees = admission_df["Total_Fees"].mean()
Average_Fees

np.float64(38636.36363636364)

In [35]:
admission_df["Total_Fees"].max()

np.int64(50000)

In [36]:
admission_df["Total_Fees"].min()

np.int64(25000)

In [37]:
admission_df

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode,Remaining_Fees,Payment_Status
0,S101,Amit,Chinchwad,Data Analytics,2026-01-10,Rahul,40000,30000,UPI,10000,Pending
1,S102,Sneha,Hadapsar,Data Science,2026-01-12,Priya,50000,50000,Cash,0,Fully Paid
2,S103,Rohit,Karve Nagar,Python Full Stack,2026-01-15,Amit,30000,20000,UPI,10000,Pending
3,S104,Pooja,Chinchwad,Data Analytics,2026-01-18,Rahul,40000,40000,Card,0,Fully Paid
4,S105,Akash,Nagpur,Java Full Stack,2026-01-20,Neha,30000,15000,UPI,15000,Pending
5,S106,Neha,Hadapsar,Testing,2026-01-22,Priya,25000,25000,Cash,0,Fully Paid
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit,50000,30000,Card,20000,Pending
7,S108,Snehal,Karve Nagar,Python Full Stack,2026-02-02,Neha,30000,30000,UPI,0,Fully Paid
8,S109,Kunal,Nagpur,Data Analytics,2026-02-05,Rahul,40000,25000,Cash,15000,Pending
9,S110,Priyanka,Hadapsar,Data Science,2026-02-08,Priya,50000,35000,UPI,15000,Pending
10,S111,Vaibhav,Chinchwad,Data Analytics,2026-02-10,Rahul,40000,20000,UPI,20000,Pending

In [38]:
ga = admission_df.groupby(by="Branch")
ga

In [39]:
ga["Paid_Fees"].sum()

Branch
Chinchwad      120000
Hadapsar       110000
Karve Nagar     50000
Nagpur          40000
Name: Paid_Fees, dtype: int64

In [40]:
gb = admission_df.groupby(by="Course")
gb

In [44]:
gb["Paid_Fees"].sum()

Course
Data Analytics       115000
Data Science         115000
Java Full Stack       15000
Python Full Stack     50000
Testing               25000
Name: Paid_Fees, dtype: int64

In [45]:
group = admission_df.groupby(by="Branch")
group

In [46]:
group["Student_ID"].count()

Branch
Chinchwad      4
Hadapsar       3
Karve Nagar    2
Nagpur         2
Name: Student_ID, dtype: int64

In [47]:
gc = admission_df.groupby(by="Course")
gc

In [48]:
gc["Student_ID"].count()

Course
Data Analytics       4
Data Science         3
Java Full Stack      1
Python Full Stack    2
Testing              1
Name: Student_ID, dtype: int64

In [49]:
gcc = admission_df.groupby(by="Counselor")
gcc

In [51]:
gcc["Paid_Fees"].sum()

Counselor
Amit      50000
Neha      45000
Priya    110000
Rahul    115000
Name: Paid_Fees, dtype: int64

In [52]:
admission_df.sort_values(by="Paid_Fees",ascending=False)

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode,Remaining_Fees,Payment_Status
1,S102,Sneha,Hadapsar,Data Science,2026-01-12,Priya,50000,50000,Cash,0,Fully Paid
3,S104,Pooja,Chinchwad,Data Analytics,2026-01-18,Rahul,40000,40000,Card,0,Fully Paid
9,S110,Priyanka,Hadapsar,Data Science,2026-02-08,Priya,50000,35000,UPI,15000,Pending
7,S108,Snehal,Karve Nagar,Python Full Stack,2026-02-02,Neha,30000,30000,UPI,0,Fully Paid
0,S101,Amit,Chinchwad,Data Analytics,2026-01-10,Rahul,40000,30000,UPI,10000,Pending
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit,50000,30000,Card,20000,Pending
8,S109,Kunal,Nagpur,Data Analytics,2026-02-05,Rahul,40000,25000,Cash,15000,Pending
5,S106,Neha,Hadapsar,Testing,2026-01-22,Priya,25000,25000,Cash,0,Fully Paid
2,S103,Rohit,Karve Nagar,Python Full Stack,2026-01-15,Amit,30000,20000,UPI,10000,Pending
10,S111,Vaibhav,Chinchwad,Data Analytics,2026-02-10,Rahul,40000,20000,UPI,20000,Pending
4,S105,Akash,Nagpur,Java Full Stack,2026-01-20,Neha,30000,15000,UPI,15000,Pending

In [53]:
admission_df.sort_values(by="Remaining_Fees", ascending=False)

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode,Remaining_Fees,Payment_Status
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit,50000,30000,Card,20000,Pending
10,S111,Vaibhav,Chinchwad,Data Analytics,2026-02-10,Rahul,40000,20000,UPI,20000,Pending
8,S109,Kunal,Nagpur,Data Analytics,2026-02-05,Rahul,40000,25000,Cash,15000,Pending
9,S110,Priyanka,Hadapsar,Data Science,2026-02-08,Priya,50000,35000,UPI,15000,Pending
4,S105,Akash,Nagpur,Java Full Stack,2026-01-20,Neha,30000,15000,UPI,15000,Pending
0,S101,Amit,Chinchwad,Data Analytics,2026-01-10,Rahul,40000,30000,UPI,10000,Pending
2,S103,Rohit,Karve Nagar,Python Full Stack,2026-01-15,Amit,30000,20000,UPI,10000,Pending
1,S102,Sneha,Hadapsar,Data Science,2026-01-12,Priya,50000,50000,Cash,0,Fully Paid
3,S104,Pooja,Chinchwad,Data Analytics,2026-01-18,Rahul,40000,40000,Card,0,Fully Paid
5,S106,Neha,Hadapsar,Testing,2026-01-22,Priya,25000,25000,Cash,0,Fully Paid
7,S108,Snehal,Karve Nagar,Python Full Stack,2026-02-02,Neha,30000,30000,UPI,0,Fully Paid

In [55]:
admission_df.sort_values(by=["Branch","Paid_Fees"])

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode,Remaining_Fees,Payment_Status
10,S111,Vaibhav,Chinchwad,Data Analytics,2026-02-10,Rahul,40000,20000,UPI,20000,Pending
0,S101,Amit,Chinchwad,Data Analytics,2026-01-10,Rahul,40000,30000,UPI,10000,Pending
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit,50000,30000,Card,20000,Pending
3,S104,Pooja,Chinchwad,Data Analytics,2026-01-18,Rahul,40000,40000,Card,0,Fully Paid
5,S106,Neha,Hadapsar,Testing,2026-01-22,Priya,25000,25000,Cash,0,Fully Paid
9,S110,Priyanka,Hadapsar,Data Science,2026-02-08,Priya,50000,35000,UPI,15000,Pending
1,S102,Sneha,Hadapsar,Data Science,2026-01-12,Priya,50000,50000,Cash,0,Fully Paid
2,S103,Rohit,Karve Nagar,Python Full Stack,2026-01-15,Amit,30000,20000,UPI,10000,Pending
7,S108,Snehal,Karve Nagar,Python Full Stack,2026-02-02,Neha,30000,30000,UPI,0,Fully Paid
4,S105,Akash,Nagpur,Java Full Stack,2026-01-20,Neha,30000,15000,UPI,15000,Pending
8,S109,Kunal,Nagpur,Data Analytics,2026-02-05,Rahul,40000,25000,Cash,15000,Pending

In [62]:
# admission_df["Branch"].unique()
len(admission_df["Branch"].unique())

4

In [63]:
# admission_df["Course"].unique()
len(admission_df["Course"].unique())

5

In [64]:
# admission_df["Counselor"].unique()
len(admission_df["Counselor"].unique())

4

In [65]:
# admission_df["Payment_Mode"].unique()
len(admission_df["Payment_Mode"].unique())

3

In [67]:
admission_df[admission_df["Paid_Fees"]>30000]

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode,Remaining_Fees,Payment_Status
1,S102,Sneha,Hadapsar,Data Science,2026-01-12,Priya,50000,50000,Cash,0,Fully Paid
3,S104,Pooja,Chinchwad,Data Analytics,2026-01-18,Rahul,40000,40000,Card,0,Fully Paid
9,S110,Priyanka,Hadapsar,Data Science,2026-02-08,Priya,50000,35000,UPI,15000,Pending

In [68]:
admission_df[admission_df["Remaining_Fees"]>10000]

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode,Remaining_Fees,Payment_Status
4,S105,Akash,Nagpur,Java Full Stack,2026-01-20,Neha,30000,15000,UPI,15000,Pending
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit,50000,30000,Card,20000,Pending
8,S109,Kunal,Nagpur,Data Analytics,2026-02-05,Rahul,40000,25000,Cash,15000,Pending
9,S110,Priyanka,Hadapsar,Data Science,2026-02-08,Priya,50000,35000,UPI,15000,Pending
10,S111,Vaibhav,Chinchwad,Data Analytics,2026-02-10,Rahul,40000,20000,UPI,20000,Pending

In [69]:
admission_df[admission_df["Course"] == "Data Science"]

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode,Remaining_Fees,Payment_Status
1,S102,Sneha,Hadapsar,Data Science,2026-01-12,Priya,50000,50000,Cash,0,Fully Paid
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit,50000,30000,Card,20000,Pending
9,S110,Priyanka,Hadapsar,Data Science,2026-02-08,Priya,50000,35000,UPI,15000,Pending

In [70]:
admission_df[admission_df["Branch"]=="Chinchwad"]

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode,Remaining_Fees,Payment_Status
0,S101,Amit,Chinchwad,Data Analytics,2026-01-10,Rahul,40000,30000,UPI,10000,Pending
3,S104,Pooja,Chinchwad,Data Analytics,2026-01-18,Rahul,40000,40000,Card,0,Fully Paid
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit,50000,30000,Card,20000,Pending
10,S111,Vaibhav,Chinchwad,Data Analytics,2026-02-10,Rahul,40000,20000,UPI,20000,Pending

In [71]:
admission_df[admission_df["Payment_Status"]=="Pending"]

,Student_ID,Student_Name,Branch,Course,Admission_Date,Counselor,Total_Fees,Paid_Fees,Payment_Mode,Remaining_Fees,Payment_Status
0,S101,Amit,Chinchwad,Data Analytics,2026-01-10,Rahul,40000,30000,UPI,10000,Pending
2,S103,Rohit,Karve Nagar,Python Full Stack,2026-01-15,Amit,30000,20000,UPI,10000,Pending
4,S105,Akash,Nagpur,Java Full Stack,2026-01-20,Neha,30000,15000,UPI,15000,Pending
6,S107,Rahul,Chinchwad,Data Science,2026-01-25,Amit,50000,30000,Card,20000,Pending
8,S109,Kunal,Nagpur,Data Analytics,2026-02-05,Rahul,40000,25000,Cash,15000,Pending
9,S110,Priyanka,Hadapsar,Data Science,2026-02-08,Priya,50000,35000,UPI,15000,Pending
10,S111,Vaibhav,Chinchwad,Data Analytics,2026-02-10,Rahul,40000,20000,UPI,20000,Pending