In [34]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_excel("data_cleaning_20_records.xlsx")
df

,Customer_ID,Customer_Name,City,Age,Course,Fees,Admission_Date,Payment_Status,Phone
0,101,Rahul Sharma,Pune,25.0,Data Analytics,40000.0,2026-01-10,Paid,9876543210
1,102,Priya patil,pune,NaN,data analytics,40000.0,10/01/2026,paid,98765 43211
2,103,Amit Kulkarni,Mumbai,31.0,Python,30000.0,2026/02/15,Pending,9876543212
3,104,sneha joshi,PUNE,29.0,Python,30000.0,15-02-2026,PAID,9876543213
4,105,VIKAS MORE,Nashik,45.0,Data Science,50000.0,2026-03-05,pending,98765-43214
5,106,Neha@123,Pune,22.0,Data Analytics,40000.0,05/03/2026,Paid,9876543215
6,107,Rohan Deshmukh,Mumbai,150.0,python,30000.0,invalid,paid,9876543216
7,108,Pooja Shinde,Pune,28.0,Data Science,50000.0,2026-04-12,Pending,9876543217
8,109,Kiran Pawar,pune,34.0,Data Analytics,40000.0,12/04/2026,Paid,9876543218
9,110,Aakash Patil,Nashik,NaN,SQL,20000.0,2026-05-20,paid,9876543219
10,111,Meena Joshi,Mumbai,27.0,SQL,20000.0,20-05-2026,PENDING,9876543220
11,112,Ravi_Deshmukh,Pune,39.0,Data Science,NaN,2026-06-08,Paid,9876543221
12,113,Anjali Kulkarni,Pune,31.0,data science,50000.0,08/06/2026,paid,9876543222
13,114,Suresh Jadhav,Nashik,42.0,Python,30000.0,2026-07-15,Pending,9876543223
14,115,Priyanka More,Mumbai,-5.0,Data Analytics,40000.0,15-07-2026,paid,9876543224
15,116,Nitin Patil,Pune,26.0,SQL,20000.0,2026-08-01,Paid,9876543225
16,117,Snehal Joshi,Pune,30.0,Python,30000.0,01/08/2026,Pending,9876543226
17,118,Akshay Pawar,Mumbai,33.0,Data Science,50000.0,2026-08-05,paid,9876543227
18,119,Pallavi Shinde,Nashik,NaN,SQL,20000.0,05-08-2026,Paid,9876543228
19,120,Rohit Kulkarni,Pune,29.0,Data Analytics,40000.0,2026-08-10,pending,12345

In [36]:
df.head()

,Customer_ID,Customer_Name,City,Age,Course,Fees,Admission_Date,Payment_Status,Phone
0,101,Rahul Sharma,Pune,25.0,Data Analytics,40000.0,2026-01-10,Paid,9876543210
1,102,Priya patil,pune,NaN,data analytics,40000.0,10/01/2026,paid,98765 43211
2,103,Amit Kulkarni,Mumbai,31.0,Python,30000.0,2026/02/15,Pending,9876543212
3,104,sneha joshi,PUNE,29.0,Python,30000.0,15-02-2026,PAID,9876543213
4,105,VIKAS MORE,Nashik,45.0,Data Science,50000.0,2026-03-05,pending,98765-43214

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     20 non-null     int64
 1   Customer_Name   20 non-null     str
 2   City            20 non-null     str
 3   Age             17 non-null     float64
 4   Course          20 non-null     str
 5   Fees            19 non-null     float64
 6   Admission_Date  20 non-null     str
 7   Payment_Status  20 non-null     str
 8   Phone           20 non-null     str
dtypes: float64(2), int64(1), str(6)
memory usage: 1.5 KB

In [38]:
df.isnull().sum()

Customer_ID       0
Customer_Name     0
City              0
Age               3
Course            0
Fees              1
Admission_Date    0
Payment_Status    0
Phone             0
dtype: int64

In [39]:
df['Customer_Name'] = df['Customer_Name'].str.strip()
df['City'] = df['City'].str.strip()
df['Course'] = df['Course'].str.strip()
df['Payment_Status'] = df['Payment_Status'].str.strip()

In [40]:
df['Customer_Name'] = df['Customer_Name'].str.title()
df['City'] = df['City'].str.title()
df['Course'] = df['Course'].str.title()
df['Payment_Status'] = df['Payment_Status'].str.title()

In [41]:
df['Customer_Name'] = (df['Customer_Name'].str.replace(r"[^A-Za-z ]","",regex=True).str.replace(r"\s+"," ",regex=True).str.strip())

In [42]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [43]:
df.loc[(df["Age"]<18) | (df["Age"]>60),"Age"]=np.nan
df["Age"] = df["Age"].fillna(df["Age"].median())

In [44]:
df["Fees"] = df["Fees"].fillna(df["Fees"].median())

In [45]:
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"],errors="coerce",dayfirst=False)
df["Admission_Date"]

0    2026-01-10
1           NaT
2           NaT
3           NaT
4    2026-03-05
5           NaT
6           NaT
7    2026-04-12
8           NaT
9    2026-05-20
10          NaT
11   2026-06-08
12          NaT
13   2026-07-15
14          NaT
15   2026-08-01
16          NaT
17   2026-08-05
18          NaT
19   2026-08-10
Name: Admission_Date, dtype: datetime64[us]

In [46]:
df[df["Admission_Date"].isna()]

,Customer_ID,Customer_Name,City,Age,Course,Fees,Admission_Date,Payment_Status,Phone
1,102,Priya Patil,Pune,30.0,Data Analytics,40000.0,NaT,Paid,98765 43211
2,103,Amit Kulkarni,Mumbai,31.0,Python,30000.0,NaT,Pending,9876543212
3,104,Sneha Joshi,Pune,29.0,Python,30000.0,NaT,Paid,9876543213
5,106,Neha,Pune,22.0,Data Analytics,40000.0,NaT,Paid,9876543215
6,107,Rohan Deshmukh,Mumbai,30.0,Python,30000.0,NaT,Paid,9876543216
8,109,Kiran Pawar,Pune,34.0,Data Analytics,40000.0,NaT,Paid,9876543218
10,111,Meena Joshi,Mumbai,27.0,Sql,20000.0,NaT,Pending,9876543220
12,113,Anjali Kulkarni,Pune,31.0,Data Science,50000.0,NaT,Paid,9876543222
14,115,Priyanka More,Mumbai,30.0,Data Analytics,40000.0,NaT,Paid,9876543224
16,117,Snehal Joshi,Pune,30.0,Python,30000.0,NaT,Pending,9876543226
18,119,Pallavi Shinde,Nashik,30.0,Sql,20000.0,NaT,Paid,9876543228

In [ ]:
df["Phone"] = df["Phone"].astype(str).str