In [35]:
import pandas as pd
import numpy as np

In [36]:
df = pd.read_excel("data_cleaning_20_records.xlsx")
df

,Customer_ID,Customer_Name,City,Age,Course,Fees,Admission_Date,Payment_Status,Phone
0,101,Rahul Sharma,Pune,25.0,Data Analytics,40000.0,2026-01-10,Paid,9876543210
1,102,Priya patil,pune,NaN,data analytics,40000.0,10/01/2026,paid,98765 43211
2,103,Amit Kulkarni,Mumbai,31.0,Python,30000.0,2026/02/15,Pending,9876543212
3,104,sneha joshi,PUNE,29.0,Python,30000.0,15-02-2026,PAID,9876543213
4,105,VIKAS MORE,Nashik,45.0,Data Science,50000.0,2026-03-05,pending,98765-43214
5,106,Neha@123,Pune,22.0,Data Analytics,40000.0,05/03/2026,Paid,9876543215
6,107,Rohan Deshmukh,Mumbai,150.0,python,30000.0,invalid,paid,9876543216
7,108,Pooja Shinde,Pune,28.0,Data Science,50000.0,2026-04-12,Pending,9876543217
8,109,Kiran Pawar,pune,34.0,Data Analytics,40000.0,12/04/2026,Paid,9876543218
9,110,Aakash Patil,Nashik,NaN,SQL,20000.0,2026-05-20,paid,9876543219
10,111,Meena Joshi,Mumbai,27.0,SQL,20000.0,20-05-2026,PENDING,9876543220
11,112,Ravi_Deshmukh,Pune,39.0,Data Science,NaN,2026-06-08,Paid,9876543221
12,113,Anjali Kulkarni,Pune,31.0,data science,50000.0,08/06/2026,paid,9876543222
13,114,Suresh Jadhav,Nashik,42.0,Python,30000.0,2026-07-15,Pending,9876543223
14,115,Priyanka More,Mumbai,-5.0,Data Analytics,40000.0,15-07-2026,paid,9876543224
15,116,Nitin Patil,Pune,26.0,SQL,20000.0,2026-08-01,Paid,9876543225
16,117,Snehal Joshi,Pune,30.0,Python,30000.0,01/08/2026,Pending,9876543226
17,118,Akshay Pawar,Mumbai,33.0,Data Science,50000.0,2026-08-05,paid,9876543227
18,119,Pallavi Shinde,Nashik,NaN,SQL,20000.0,05-08-2026,Paid,9876543228
19,120,Rohit Kulkarni,Pune,29.0,Data Analytics,40000.0,2026-08-10,pending,12345

In [37]:
df.head()

,Customer_ID,Customer_Name,City,Age,Course,Fees,Admission_Date,Payment_Status,Phone
0,101,Rahul Sharma,Pune,25.0,Data Analytics,40000.0,2026-01-10,Paid,9876543210
1,102,Priya patil,pune,NaN,data analytics,40000.0,10/01/2026,paid,98765 43211
2,103,Amit Kulkarni,Mumbai,31.0,Python,30000.0,2026/02/15,Pending,9876543212
3,104,sneha joshi,PUNE,29.0,Python,30000.0,15-02-2026,PAID,9876543213
4,105,VIKAS MORE,Nashik,45.0,Data Science,50000.0,2026-03-05,pending,98765-43214

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     20 non-null     int64
 1   Customer_Name   20 non-null     str
 2   City            20 non-null     str
 3   Age             17 non-null     float64
 4   Course          20 non-null     str
 5   Fees            19 non-null     float64
 6   Admission_Date  20 non-null     str
 7   Payment_Status  20 non-null     str
 8   Phone           20 non-null     str
dtypes: float64(2), int64(1), str(6)
memory usage: 1.5 KB

In [39]:
df.isnull().sum()

Customer_ID       0
Customer_Name     0
City              0
Age               3
Course            0
Fees              1
Admission_Date    0
Payment_Status    0
Phone             0
dtype: int64

In [40]:
df['Customer_Name'] = df['Customer_Name'].str.strip()
df['City'] = df['City'].str.strip()
df['Course'] = df['Course'].str.strip()
df['Payment_Status'] = df['Payment_Status'].str.strip()

In [41]:
df['Customer_Name'] = df['Customer_Name'].str.title()
df['City'] = df['City'].str.title()
df['Course'] = df['Course'].str.title()
df['Payment_Status'] = df['Payment_Status'].str.title()

In [42]:
df['Customer_Name'] = (df['Customer_Name'].str.replace(r"[^A-Za-z ]","",regex=True).str.replace(r"\s+"," ",regex=True).str.strip())

In [43]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [44]:
df.loc[(df["Age"]<18) | (df["Age"]>60),"Age"]=np.nan
df["Age"] = df["Age"].fillna(df["Age"].median())

In [45]:
df["Fees"] = df["Fees"].fillna(df["Fees"].median())

In [46]:
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"],errors="coerce",dayfirst=False)
df["Admission_Date"]

0    2026-01-10
1           NaT
2           NaT
3           NaT
4    2026-03-05
5           NaT
6           NaT
7    2026-04-12
8           NaT
9    2026-05-20
10          NaT
11   2026-06-08
12          NaT
13   2026-07-15
14          NaT
15   2026-08-01
16          NaT
17   2026-08-05
18          NaT
19   2026-08-10
Name: Admission_Date, dtype: datetime64[us]

In [47]:
df[df["Admission_Date"].isna()]

,Customer_ID,Customer_Name,City,Age,Course,Fees,Admission_Date,Payment_Status,Phone
1,102,Priya Patil,Pune,30.0,Data Analytics,40000.0,NaT,Paid,98765 43211
2,103,Amit Kulkarni,Mumbai,31.0,Python,30000.0,NaT,Pending,9876543212
3,104,Sneha Joshi,Pune,29.0,Python,30000.0,NaT,Paid,9876543213
5,106,Neha,Pune,22.0,Data Analytics,40000.0,NaT,Paid,9876543215
6,107,Rohan Deshmukh,Mumbai,30.0,Python,30000.0,NaT,Paid,9876543216
8,109,Kiran Pawar,Pune,34.0,Data Analytics,40000.0,NaT,Paid,9876543218
10,111,Meena Joshi,Mumbai,27.0,Sql,20000.0,NaT,Pending,9876543220
12,113,Anjali Kulkarni,Pune,31.0,Data Science,50000.0,NaT,Paid,9876543222
14,115,Priyanka More,Mumbai,30.0,Data Analytics,40000.0,NaT,Paid,9876543224
16,117,Snehal Joshi,Pune,30.0,Python,30000.0,NaT,Pending,9876543226
18,119,Pallavi Shinde,Nashik,30.0,Sql,20000.0,NaT,Paid,9876543228

In [48]:
df["Phone"] = (
    df["Phone"]
    .astype(str)
    .str.replace(r"[\s-]", "", regex=True)
)
df

,Customer_ID,Customer_Name,City,Age,Course,Fees,Admission_Date,Payment_Status,Phone
0,101,Rahul Sharma,Pune,25.0,Data Analytics,40000.0,2026-01-10,Paid,9876543210
1,102,Priya Patil,Pune,30.0,Data Analytics,40000.0,NaT,Paid,9876543211
2,103,Amit Kulkarni,Mumbai,31.0,Python,30000.0,NaT,Pending,9876543212
3,104,Sneha Joshi,Pune,29.0,Python,30000.0,NaT,Paid,9876543213
4,105,Vikas More,Nashik,45.0,Data Science,50000.0,2026-03-05,Pending,9876543214
5,106,Neha,Pune,22.0,Data Analytics,40000.0,NaT,Paid,9876543215
6,107,Rohan Deshmukh,Mumbai,30.0,Python,30000.0,NaT,Paid,9876543216
7,108,Pooja Shinde,Pune,28.0,Data Science,50000.0,2026-04-12,Pending,9876543217
8,109,Kiran Pawar,Pune,34.0,Data Analytics,40000.0,NaT,Paid,9876543218
9,110,Aakash Patil,Nashik,30.0,Sql,20000.0,2026-05-20,Paid,9876543219
10,111,Meena Joshi,Mumbai,27.0,Sql,20000.0,NaT,Pending,9876543220
11,112,RaviDeshmukh,Pune,39.0,Data Science,40000.0,2026-06-08,Paid,9876543221
12,113,Anjali Kulkarni,Pune,31.0,Data Science,50000.0,NaT,Paid,9876543222
13,114,Suresh Jadhav,Nashik,42.0,Python,30000.0,2026-07-15,Pending,9876543223
14,115,Priyanka More,Mumbai,30.0,Data Analytics,40000.0,NaT,Paid,9876543224
15,116,Nitin Patil,Pune,26.0,Sql,20000.0,2026-08-01,Paid,9876543225
16,117,Snehal Joshi,Pune,30.0,Python,30000.0,NaT,Pending,9876543226
17,118,Akshay Pawar,Mumbai,33.0,Data Science,50000.0,2026-08-05,Paid,9876543227
18,119,Pallavi Shinde,Nashik,30.0,Sql,20000.0,NaT,Paid,9876543228
19,120,Rohit Kulkarni,Pune,29.0,Data Analytics,40000.0,2026-08-10,Pending,12345

In [49]:
df["Phone_Valid"] = df["Phone"].str.match(r"^[6-9]\d{9}$")
print(df[["Phone","Phone_Valid"]])

         Phone  Phone_Valid
0   9876543210         True
1   9876543211         True
2   9876543212         True
3   9876543213         True
4   9876543214         True
5   9876543215         True
6   9876543216         True
7   9876543217         True
8   9876543218         True
9   9876543219         True
10  9876543220         True
11  9876543221         True
12  9876543222         True
13  9876543223         True
14  9876543224         True
15  9876543225         True
16  9876543226         True
17  9876543227         True
18  9876543228         True
19       12345        False

In [50]:
df["Payment_Status"] = (df["Payment_Status"].str.strip().str.title())
df["Payment_Status"].value_counts()

Payment_Status
Paid       13
Pending     7
Name: count, dtype: int64

In [51]:
df.duplicated().sum()

np.int64(0)

In [52]:
df[df["Customer_ID"].duplicated(keep=False)]

Empty DataFrame
Columns: [Customer_ID, Customer_Name, City, Age, Course, Fees, Admission_Date, Payment_Status, Phone, Phone_Valid]
Index: []

In [53]:
df["Age_group"] = pd.cut(
    df["Age"],bins=[0,25,35,45,100],
    labels=[
        "18-25",
        "26-35",
        "36-45",
        "46+"
    ]
)
df

,Customer_ID,Customer_Name,City,Age,Course,Fees,Admission_Date,Payment_Status,Phone,Phone_Valid,Age_group
0,101,Rahul Sharma,Pune,25.0,Data Analytics,40000.0,2026-01-10,Paid,9876543210,True,18-25
1,102,Priya Patil,Pune,30.0,Data Analytics,40000.0,NaT,Paid,9876543211,True,26-35
2,103,Amit Kulkarni,Mumbai,31.0,Python,30000.0,NaT,Pending,9876543212,True,26-35
3,104,Sneha Joshi,Pune,29.0,Python,30000.0,NaT,Paid,9876543213,True,26-35
4,105,Vikas More,Nashik,45.0,Data Science,50000.0,2026-03-05,Pending,9876543214,True,36-45
5,106,Neha,Pune,22.0,Data Analytics,40000.0,NaT,Paid,9876543215,True,18-25
6,107,Rohan Deshmukh,Mumbai,30.0,Python,30000.0,NaT,Paid,9876543216,True,26-35
7,108,Pooja Shinde,Pune,28.0,Data Science,50000.0,2026-04-12,Pending,9876543217,True,26-35
8,109,Kiran Pawar,Pune,34.0,Data Analytics,40000.0,NaT,Paid,9876543218,True,26-35
9,110,Aakash Patil,Nashik,30.0,Sql,20000.0,2026-05-20,Paid,9876543219,True,26-35
10,111,Meena Joshi,Mumbai,27.0,Sql,20000.0,NaT,Pending,9876543220,True,26-35
11,112,RaviDeshmukh,Pune,39.0,Data Science,40000.0,2026-06-08,Paid,9876543221,True,36-45
12,113,Anjali Kulkarni,Pune,31.0,Data Science,50000.0,NaT,Paid,9876543222,True,26-35
13,114,Suresh Jadhav,Nashik,42.0,Python,30000.0,2026-07-15,Pending,9876543223,True,36-45
14,115,Priyanka More,Mumbai,30.0,Data Analytics,40000.0,NaT,Paid,9876543224,True,26-35
15,116,Nitin Patil,Pune,26.0,Sql,20000.0,2026-08-01,Paid,9876543225,True,26-35
16,117,Snehal Joshi,Pune,30.0,Python,30000.0,NaT,Pending,9876543226,True,26-35
17,118,Akshay Pawar,Mumbai,33.0,Data Science,50000.0,2026-08-05,Paid,9876543227,True,26-35
18,119,Pallavi Shinde,Nashik,30.0,Sql,20000.0,NaT,Paid,9876543228,True,26-35
19,120,Rohit Kulkarni,Pune,29.0,Data Analytics,40000.0,2026-08-10,Pending,12345,False,26-35

In [54]:
df["Fee_Category"] = pd.cut(
    df["Fees"],
    bins=[0,25000,40000,60000],
    labels=[
        "Low",
        "Medium",
        "High"
    ]
)
df

,Customer_ID,Customer_Name,City,Age,Course,Fees,Admission_Date,Payment_Status,Phone,Phone_Valid,Age_group,Fee_Category
0,101,Rahul Sharma,Pune,25.0,Data Analytics,40000.0,2026-01-10,Paid,9876543210,True,18-25,Medium
1,102,Priya Patil,Pune,30.0,Data Analytics,40000.0,NaT,Paid,9876543211,True,26-35,Medium
2,103,Amit Kulkarni,Mumbai,31.0,Python,30000.0,NaT,Pending,9876543212,True,26-35,Medium
3,104,Sneha Joshi,Pune,29.0,Python,30000.0,NaT,Paid,9876543213,True,26-35,Medium
4,105,Vikas More,Nashik,45.0,Data Science,50000.0,2026-03-05,Pending,9876543214,True,36-45,High
5,106,Neha,Pune,22.0,Data Analytics,40000.0,NaT,Paid,9876543215,True,18-25,Medium
6,107,Rohan Deshmukh,Mumbai,30.0,Python,30000.0,NaT,Paid,9876543216,True,26-35,Medium
7,108,Pooja Shinde,Pune,28.0,Data Science,50000.0,2026-04-12,Pending,9876543217,True,26-35,High
8,109,Kiran Pawar,Pune,34.0,Data Analytics,40000.0,NaT,Paid,9876543218,True,26-35,Medium
9,110,Aakash Patil,Nashik,30.0,Sql,20000.0,2026-05-20,Paid,9876543219,True,26-35,Low
10,111,Meena Joshi,Mumbai,27.0,Sql,20000.0,NaT,Pending,9876543220,True,26-35,Low
11,112,RaviDeshmukh,Pune,39.0,Data Science,40000.0,2026-06-08,Paid,9876543221,True,36-45,Medium
12,113,Anjali Kulkarni,Pune,31.0,Data Science,50000.0,NaT,Paid,9876543222,True,26-35,High
13,114,Suresh Jadhav,Nashik,42.0,Python,30000.0,2026-07-15,Pending,9876543223,True,36-45,Medium
14,115,Priyanka More,Mumbai,30.0,Data Analytics,40000.0,NaT,Paid,9876543224,True,26-35,Medium
15,116,Nitin Patil,Pune,26.0,Sql,20000.0,2026-08-01,Paid,9876543225,True,26-35,Low
16,117,Snehal Joshi,Pune,30.0,Python,30000.0,NaT,Pending,9876543226,True,26-35,Medium
17,118,Akshay Pawar,Mumbai,33.0,Data Science,50000.0,2026-08-05,Paid,9876543227,True,26-35,High
18,119,Pallavi Shinde,Nashik,30.0,Sql,20000.0,NaT,Paid,9876543228,True,26-35,Low
19,120,Rohit Kulkarni,Pune,29.0,Data Analytics,40000.0,2026-08-10,Pending,12345,False,26-35,Medium

In [55]:
df = df[df["Phone_Valid"]==True]

In [56]:
df.drop(columns=["Phone_Valid"], inplace=True)

In [57]:
df.reset_index(drop=True,inplace=True)

In [61]:
df
df.isnull().sum()

Customer_ID        0
Customer_Name      0
City               0
Age                0
Course             0
Fees               0
Admission_Date    11
Payment_Status     0
Phone              0
Age_group          0
Fee_Category       0
dtype: int64

In [63]:
df.dtypes

Customer_ID                int64
Customer_Name                str
City                         str
Age                      float64
Course                       str
Fees                     float64
Admission_Date    datetime64[us]
Payment_Status               str
Phone                        str
Age_group               category
Fee_Category            category
dtype: object

In [ ]:
df.to_excel("cleaned_customer_data.xlsx",index=False)