In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [14]:
# df = pd.read_csv("retail_sales_100_records.csv")
# df

In [15]:
df = pd.read_csv("retail_sales_100_records.csv")
df.head()

         Date     Product  Region  Sales   Profit
0  01-01-2026  Headphones  Nashik   5530   834.81
1  02-01-2026  Smartwatch  Nagpur   6748  1334.17
2  03-01-2026      Tablet    Pune  29971  3641.52
3  04-01-2026  Smartwatch  Nashik  10994  1483.58
4  05-01-2026  Smartwatch  Nashik   4495   896.81

In [16]:
df.tail()

          Date     Product  Region  Sales    Profit
95  06-04-2026      Tablet    Pune  26358   3791.57
96  07-04-2026  Smartwatch  Nagpur   8919   1590.33
97  08-04-2026      Mobile  Nagpur  25853   3510.47
98  09-04-2026      Mobile  Mumbai  28769   4955.45
99  10-04-2026      Laptop  Nashik  61148  13612.69

In [17]:
df.head(10)

         Date     Product  Region  Sales   Profit
0  01-01-2026  Headphones  Nashik   5530   834.81
1  02-01-2026  Smartwatch  Nagpur   6748  1334.17
2  03-01-2026      Tablet    Pune  29971  3641.52
3  04-01-2026  Smartwatch  Nashik  10994  1483.58
4  05-01-2026  Smartwatch  Nashik   4495   896.81
5  06-01-2026      Mobile  Mumbai  30232  2752.07
6  07-01-2026      Tablet    Pune  23585  5745.68
7  08-01-2026      Tablet  Nashik  20581  4082.69
8  09-01-2026      Tablet  Nagpur  24554  3220.24
9  10-01-2026  Smartwatch  Nagpur   6696  1671.43

In [18]:
df.shape[0]

100

In [19]:
df.shape[1]

5

In [20]:
df.columns

Index(['Date', 'Product', 'Region', 'Sales', 'Profit'], dtype='str')

In [21]:
df.dtypes

Date           str
Product        str
Region         str
Sales        int64
Profit     float64
dtype: object

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     100 non-null    str
 1   Product  100 non-null    str
 2   Region   100 non-null    str
 3   Sales    100 non-null    int64
 4   Profit   100 non-null    float64
dtypes: float64(1), int64(1), str(3)
memory usage: 4.0 KB

In [23]:
df.describe()

              Sales        Profit
count    100.000000    100.000000
mean   25154.450000   4668.376700
std    21418.490638   4612.618965
min      698.000000    128.170000
25%     6834.250000   1275.702500
50%    21824.000000   3183.145000
75%    33505.250000   6314.492500
max    72323.000000  15957.630000

In [24]:
df["Date"]=pd.to_datetime(df["Date"],dayfirst=True)
df

         Date     Product  Region  Sales    Profit
0  2026-01-01  Headphones  Nashik   5530    834.81
1  2026-01-02  Smartwatch  Nagpur   6748   1334.17
2  2026-01-03      Tablet    Pune  29971   3641.52
3  2026-01-04  Smartwatch  Nashik  10994   1483.58
4  2026-01-05  Smartwatch  Nashik   4495    896.81
..        ...         ...     ...    ...       ...
95 2026-04-06      Tablet    Pune  26358   3791.57
96 2026-04-07  Smartwatch  Nagpur   8919   1590.33
97 2026-04-08      Mobile  Nagpur  25853   3510.47
98 2026-04-09      Mobile  Mumbai  28769   4955.45
99 2026-04-10      Laptop  Nashik  61148  13612.69

[100 rows x 5 columns]

In [30]:
df["Year"] = df["Date"].dt.year
df["Year"]

0     2026
1     2026
2     2026
3     2026
4     2026
      ...
95    2026
96    2026
97    2026
98    2026
99    2026
Name: Year, Length: 100, dtype: int32

In [31]:
df["Month"] = df["Date"].dt.month
df["Month"]

0     1
1     1
2     1
3     1
4     1
     ..
95    4
96    4
97    4
98    4
99    4
Name: Month, Length: 100, dtype: int32

In [34]:
df["Month Name"] = df["Date"].dt.month_name()
df["Month Name"]

0     January
1     January
2     January
3     January
4     January
       ...
95      April
96      April
97      April
98      April
99      April
Name: Month Name, Length: 100, dtype: str

In [35]:
df["Day"] = df["Date"].dt.day
df['Day']

0      1
1      2
2      3
3      4
4      5
      ..
95     6
96     7
97     8
98     9
99    10
Name: Day, Length: 100, dtype: int32

In [37]:
df["Day Name"] = df["Date"].dt.day_name()
df["Day Name"]

0      Thursday
1        Friday
2      Saturday
3        Sunday
4        Monday
        ...
95       Monday
96      Tuesday
97    Wednesday
98     Thursday
99       Friday
Name: Day Name, Length: 100, dtype: str

In [38]:
df.isnull().sum()

Date          0
Product       0
Region        0
Sales         0
Profit        0
Year          0
Month         0
Month Name    0
Day           0
Day Name      0
dtype: int64

In [41]:
df.duplicated().sum()

np.int64(0)

In [46]:
df[df["Sales"]<=0]

Empty DataFrame
Columns: [Date, Product, Region, Sales, Profit, Year, Month, Month Name, Day, Day Name]
Index: []

In [48]:
df[df["Profit"]<=0]

Empty DataFrame
Columns: [Date, Product, Region, Sales, Profit, Year, Month, Month Name, Day, Day Name]
Index: []